### ISSUE TITLE
很多错误提示

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#100]
### 问题描述？

很多SyntaxError
23:09:35.513 > 61 |     display: inline-block;
23:09:35.513 (537:14) Unclosed bracket
23:09:35.513      |    ^
23:09:35.518   535 |     top: 0;
23:09:35.518   62 |     position: relative;
23:09:35.518   536 |     /*   #ifdef  H5   */
23:09:35.518   63 |     bottom: -58rpx;
23:09:35.523 > 537 |     top: calc(88rpx + constant(safe-area-inset-top);
23:09:35.523 Module build failed (from ./node_modules/postcss-loader/src/index.js):
23:09:35.524       |              ^
23:09:35.524 SyntaxError
23:09:35.529   538 |     top: calc(88rpx + env(safe-area-inset-top);
23:09:35.529 (65:4) Unclosed bracket
23:09:35.530   539 |     /*   #endif   */
23:09:35.530   63 |     flex: 1;
23:09:35.537 Module build failed (from ./node_modules/postcss-loader/src/index.js):
23:09:35.537   64 |     font-size: 34rpx;
23:09:35.538 SyntaxError
23:09:35.538 > 65 |     color: #000;
23:09:35.542 (61:4) Unclosed bracket
23:09:35.543      |    ^
23:09:35.543   59 | 这种错误

**Comment by zhangdaren** [comment]
已解决

**Comment by zhangdaren** [comment]
`
xxxxx/xxxx.vue:176:3: Unknown word
`
目前发现还是有这个问题，
如果碰到这个错误，那么，肯定是这个vue文件里面引用的css里面的语法问题，把
搜索 ifdef ，可能变成了两行，把换行删除就行了，，

预计下个版本修复。

**Comment by zhangdaren** [comment]
已修复
