### ISSUE TITLE
微信小程序”简易双向绑定“转换错误

### ISSUE THREAD

**Issue by zhifengjiang** [zhangdaren/miniprogram-to-uniapp#109]
### 问题描述？
微信小程序 [简易双向绑定](https://developers.weixin.qq.com/miniprogram/dev/framework/view/two-way-bindings.html)应转为[v-model](https://uniapp.dcloud.io/vue-basics?id=v-model)

**Comment by zhangdaren3389** [comment]
收到~~

**Comment by zhangdaren** [comment]
已解决

**Comment by zhangdaren** [comment]
已解决
