### ISSUE TITLE
小程序for循环里的字段名被设置为了data字段

### ISSUE THREAD

**Issue by zhifengjiang** [zhangdaren/miniprogram-to-uniapp#110]
### 问题描述？
小程序for循环里的字段名(symbolItem.name)，被设置为了data
`

<van-tabs class="top symbols" active="{{activeTab}}">

            <van-tab class="vantab" wx:for='{{symbolTypes}}' wx:for-item='symbolItem' wx:key='name' title="{{symbolItem.name}}">

                <text class="symbol" wx:for='{{symbolItem.symbols}}' wx:for-item='symbol' wx:key='*this' bind:tap='insertSymbol'
                    data-symbol='{{symbol}}'>{{symbol}}</text>
            </van-tab>

`
uniapp:

![image](https://user-images.githubusercontent.com/6251979/121663758-52280300-cad9-11eb-85f2-178646d22e0c.png)

### 期望的结果
不应该有这个data字段

**Comment by zhangdaren** [comment]
感谢反馈，已记录~

**Comment by zhangdaren** [comment]
v2.0.3已修复
