### ISSUE TITLE
微信小程序转后，自定义组件和vant组件路径不对，找不到文件

### ISSUE THREAD

**Issue by anihCevol** [zhangdaren/miniprogram-to-uniapp#115]
### 问题描述？

![image](https://user-images.githubusercontent.com/42430384/130042555-1adfef70-91fc-4e18-ae58-81373b33b53e.png)

**Comment by zhangdaren** [comment]
vant暂时没啥太好的办法，，，文件查找失败是路径不对，，

目前 来说，vant建议：
1. 替换为uview（转换时不使用-z)
2. 参照uniapp引入wxcomponents的方式引入vant组件
