### ISSUE TITLE
转出后只有css

### ISSUE THREAD

**Issue by zhaozhinan** [zhangdaren/miniprogram-to-uniapp#117]
### 问题描述？
转出后只有css
版本：1.1.5

### 重现步骤
命令转出 成功后 项目结构都有 但是文件夹里只有css文件；

### 期望的结果
期望是一个完整的uniapp项目

**Comment by zhangdaren** [comment]
请加作者qq或qq群解决问题，应该是命令行报错了，

**Comment by zhangdaren** [comment]
v2.0.3已修复
