### ISSUE TITLE
转换时一直卡住不动

### ISSUE THREAD

**Issue by all-resonance** [zhangdaren/miniprogram-to-uniapp#118]
### 问题描述？
![image](https://user-images.githubusercontent.com/24592171/132278975-ab6d51d0-3e30-41cf-8fd0-337770da7986.png)

**Comment by zhangdaren** [comment]
可能已经 报错了，请暂时使用npm包进行转换吧，可能会报错，请使用qq三群里的文件替换一下，再转换，，预计新版在十一期间发布，感谢支持

**Comment by zhangdaren** [comment]
v2.0.3已修复
