### ISSUE TITLE
建议忽略自定义tabbar转换

### ISSUE THREAD

**Issue by jiyeme** [zhangdaren/miniprogram-to-uniapp#119]
### 问题描述？

自定义的`tabbar`被处理成`index.vue`
建议忽略自定义tabbar转换

### 重现步骤

按介绍操作一遍

### 期望的结果

原封不动的复制`custom-tab-bar`文件夹

理由：

> https://uniapp.dcloud.io/collocation/pages?id=custom-tab-bar
微信小程序自定义tabbar：微信提供一直基于webview自定义tabBar的方案。该功能体验不佳，不太推荐使用。如果要使用，参考微信文档，项目根创建 custom-tab-bar 目录，注意里边的代码是 wxml,wxss，不是 vue，uni-app编译器会**直接拷贝**该目录到微信小程序中

**Comment by zhangdaren** [comment]
感谢建议，新版会这么做的。预计十一期间发布。

**Comment by zhangdaren** [comment]
已解决，v2.0.3最新版。
