### ISSUE TITLE
app.json中的usingComponents没有转为全局组件

### ISSUE THREAD

**Issue by oyai32** [zhangdaren/miniprogram-to-uniapp#122]
app.json中的usingComponents没有转为全局组件，需要自己额外再注册

**Comment by zhangdaren** [comment]
已经转换为pages.json里面easycom注册了哇

**Comment by oyai32** [comment]
确实都注册到easycom了，但是编译后node-modules确少文件，显示组件未找到，知道什么原因吗？
![image](https://user-images.githubusercontent.com/12603926/140253352-a7ddf378-0e12-4b91-9215-10832327006f.png)
![image](https://user-images.githubusercontent.com/12603926/140253385-9c775119-c501-4142-a4f7-1e9aa16f09cd.png)

**Comment by oyai32** [comment]
解决了，路径前面需要加@/，重新编译后也不会出现node-modles这个文件夹
![image](https://user-images.githubusercontent.com/12603926/140259846-1ad0ab29-c4ce-4eec-a5bc-370f732165ef.png)
![image](https://user-images.githubusercontent.com/12603926/140259860-0a1afa66-eb00-46c5-a998-aa6df55535a9.png)

**Comment by zhangdaren** [comment]
v2.1.1已对这些

**Comment by calvinlsy86** [comment]
![image](https://github.com/zhangdaren/miniprogram-to-uniapp/assets/160718114/24cdf350-93a2-444b-970d-75002defef87)
为什么生成的全局组件，前面有这些符号？

**Comment by calvinlsy86** [comment]
![image](https://github.com/zhangdaren/miniprogram-to-uniapp/assets/160718114/c058808c-aab1-43fa-ae70-9182de016223)
为什么生成的全局组件名称前面带这些符号？
<img width="556" alt="image" src="https://github.com/zhangdaren/miniprogram-to-uniapp/assets/160718114/195770f8-9235-4ea7-8c6c-c7f39537a2e7">
