### ISSUE TITLE
wx.api转为uni.api会有问题

### ISSUE THREAD

**Issue by oyai32** [zhangdaren/miniprogram-to-uniapp#125]
### 问题描述？
目前，wx.api会直接被转为 uni.api，如
` 
const res = await wx.showModal({
      content: '确定吗'
});
`
会直接转为
`
const res = await uni.showModal({
      content: '确定吗'
});
`
但uni对api的promise封装，返回数据的第一个参数是错误对象，第二个参数是返回数据。
故，应该是
`
const [err, res] = await uni.showModal({
      content: '确定吗'
});
`

**Comment by zhangdaren** [comment]
这样啊，，我研究一下，感谢~

**Comment by zhangdaren** [comment]
v2.1.1已处理
