### ISSUE TITLE
转换后的图片路径变成了绝对路径

### ISSUE THREAD

**Issue by zsedcbm** [zhangdaren/miniprogram-to-uniapp#128]
### 问题描述？

```
// 转换前
  <image mode="widthFix" :src="image_url + 'loading.gif'"></image>

// 转换后
   <image mode="widthFix" :src="image_url + '/static/counsel/loading.gif'"></image>
```
由于小程序体积限制，所以项目中的图片都放到了oss上面，这里的图片调用改为 变量+图片名称，转换后被程序追加了签名一串路径。

### 期望的结果

能否加个配置项，允许不转换路径

**Comment by zhangdaren** [comment]
感谢反馈，，我研究一下，，预计下版本修复一下这种问题

**Comment by zhangdaren** [comment]
刚刚测试，最新版不会对这种情况进行转换了，，

// 转换前
<image mode="widthFix" src="{{image_url}}loading.gif"></image>

// 转换后
<image mode="widthFix" :src="image_url + 'loading.gif'"></image>

**Comment by zsedcbm** [comment]
更新新版后貌似.git目录也会触发转换？

**Comment by zhangdaren** [comment]
有影响嘛？我下版去掉吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月17日(星期四) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 转换后的图片路径变成了绝对路径 (Issue #128)





 
更新新版后貌似.git目录也会触发转换？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zsedcbm** [comment]
js部分转换后还是会转换路径

**Comment by zhangdaren** [comment]
> js部分转换后还是会转换路径

试举一例？

**Comment by zsedcbm** [comment]
```
  data() {
    return {
      image_url: globalData.image_url,
      addImg: globalData.image_url + 'addPic.png'
   }
}
```
转换后
```
  data() {
    return {
      image_url: globalData.image_url,
      addImg: globalData.image_url + '/static/pages/addZd/addPic.png'
   }
}
```

**Comment by zsedcbm** [comment]
```
msg.sendContent.indexOf('.png') > -1
```

转换后

```
msg.sendContent.indexOf('/static/pages/counselChat/.png') > -1
```

**Comment by zhangdaren** [comment]
> ```
>   data() {
>     return {
>       image_url: globalData.image_url,
>       addImg: globalData.image_url + 'addPic.png'
>    }
> }
> ```
> 
> 
>     
>   
> 
> 转换后
> 
> 
> ```
>   data() {
>     return {
>       image_url: globalData.image_url,
>       addImg: globalData.image_url + '/static/pages/addZd/addPic.png'
>    }
> }
> ```

收到，谢谢，这里确实 不用替换~下版本修复~
