### ISSUE TITLE
Failed to resolve loader: gltf-loader

### ISSUE THREAD

**Issue by shilcheng** [zhangdaren/miniprogram-to-uniapp#130]
### 问题描述？
进度 [############################--] 5/bps 93% 3.7s 异常：replaceTemplateTag - attrs  undefined
进度 [##############################] 5/bps 100% 0.0s 
write pages.json success!
write manifest.json success!
write main.js success!

统计信息：

vue文件数量: 111
支付api数量: 1
登录api数量: 4

恭喜你，转换完成！
用时: 57.607s
转换完成，但是在hbuilderx里 运行报下面错误

17:24:07.339 Failed to resolve loader: gltf-loader
17:24:07.339 You may need to install it.
17:24:07.340  at utils/model.js:1
17:24:07.340 文件查找失败：'orbit' at utils/model.js:2

**Comment by zhangdaren** [comment]
略过吧，，不影响转换结果。
