### ISSUE TITLE
hidden属性高反了

### ISSUE THREAD

**Issue by zsedcbm** [zhangdaren/miniprogram-to-uniapp#132]
### 问题描述？

在小程序里面，hidden属性表示隐藏，vue里面 v-if 表示显示，使用hidden属性时组件会渲染只是隐藏，切换的时候性能比 v-if 重新渲染要好一点，建议替换成 v-show并取反。

### 期望的结果

hidden属性 生成 v-show 并条件取反。

**Comment by zhangdaren** [comment]
好像现有版本没有这个问题，，用v-show在某些时候不生效。。。暂未细究，未找到原因。。。因此可能不打算换v-show了
