### ISSUE TITLE
转换的时候没有排除 .git 目录

### ISSUE THREAD

**Issue by zsedcbm** [zhangdaren/miniprogram-to-uniapp#133]
### 问题描述？

如题，老项目使用git管理版本，hbuildx 打开项目后，直接右键转换，由于.git 目录中文件比较多，经常转换到一半 hbuildx 会自动关闭。

### 期望的结果

建议项目转换的时候，默认排除掉 版本日志目录

**Comment by zhangdaren** [comment]
感谢，收到，，新版hbx将排除掉.开头的目录，目前npm版本工具已经排除了。
