### ISSUE TITLE
转换后编译报block节点错误

### ISSUE THREAD

**Issue by matthuo333** [zhangdaren/miniprogram-to-uniapp#134]
### 问题描述？
Module build failed (from ./node_modules/postcss-loader/src/index.js):
20:23:31.269 SyntaxError
20:23:31.281 (2:2) Unknown word
20:23:31.282   1 | <template>
20:23:31.294 > 2 | 	<block>
20:23:31.295     | 	^
20:23:31.308   3 |         <view class="weui-search-bar">
20:23:31.308   4 |             <view class="weui-search-bar__form">

### 重现步骤

![image](https://user-images.githubusercontent.com/55862904/160123719-bc83ceae-7bee-44fd-a51a-7cb8426f0d7c.png)

### 期望的结果
编译顺利通过

**Comment by zhangdaren** [comment]
将block改成view标签吧，，npm工具已经修复此问题，hbx工具待修复
