### ISSUE TITLE
微信小程序转uni时，出现部分wxml丢失

### ISSUE THREAD

**Issue by CJL92** [zhangdaren/miniprogram-to-uniapp#148]
### 问题描述？
wtu -V
2.0.24

wtu -i 路径
微信小程序转uni时，出现部分wxml和css丢失,但js又转换成功的

**Comment by zhangdaren** [comment]
可否具体说说？

**Comment by CJL92** [comment]
就是直接按步骤使用时，导入一套完整的代码，用uni编译小程序时，发现里面部分的页面和样式直接没有生成。我把项目copy到不同的文件夹，多次尝试，都是会丢失页面和样式。js却是准确的生成了

**Comment by zhangdaren** [comment]
可以提供一份测试demo吗？最小可复现bug的demo就行了。另外，transfrom.log也提供一下

**Comment by CJL92** [comment]
相关代码移除了，只保留一直会转换失败的页面，见谅


ゞ荒城旧梦﹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangdaren/miniprogram-to-uniapp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 上午9:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhangdaren/miniprogram-to-uniapp] 微信小程序转uni时，出现部分wxml丢失 (Issue #148)





 
可以提供一份测试demo吗？最小可复现bug的demo就行了。另外，transfrom.log也提供一下

**Comment by CJL92** [comment]
请问直接在邮件中发你的附件收到了吧

**Comment by zhangdaren** [comment]
没收到，请直接发到： ***@***.***
&nbsp;


张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 上午9:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 微信小程序转uni时，出现部分wxml丢失 (Issue #148)





 
请问直接在邮件中发你的附件收到了吧
 
&mdash;

**Comment by CJL92** [comment]
我这边无法看到您的邮箱，被git这边转成了星号，我直接放到百度云盘中，您去下载下  ，地址 ： 链接: https://pan.baidu.com/s/1kKm46CLsOZ11PcZ5YJFFsA 提取码: nucl

**Comment by zhangdaren** [comment]
收到，我先看一下&nbsp;


张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 上午9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 微信小程序转uni时，出现部分wxml丢失 (Issue #148)





 
我这边无法看到您的邮箱，被git这边转成了星号，我直接放到百度云盘中，您去下载下  ，地址 ： 链接: https://pan.baidu.com/s/1kKm46CLsOZ11PcZ5YJFFsA 提取码: nucl
 
&mdash;

**Comment by zhangdaren** [comment]
经过排查，是```<input class='iptbox {{index === focusIndex?\'show\':\'hide\'}}' onKeyUp="value=value.replace(/[^\d|chun]/g,'')" value="{{validaPicCode.length&gt;=index+1?validaPicCode[index]:''}}" disabled password='{{ispassword}}' catchtap='Tap'&gt;</input&gt;``` 解析出的问题，，，预计下版修复 ，，&nbsp; 可以 手动将 \' 替换为'' 再进行替换吧。
&nbsp;


张鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 上午9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 微信小程序转uni时，出现部分wxml丢失 (Issue #148)





 
我这边无法看到您的邮箱，被git这边转成了星号，我直接放到百度云盘中，您去下载下  ，地址 ： 链接: https://pan.baidu.com/s/1kKm46CLsOZ11PcZ5YJFFsA 提取码: nucl
 
&mdash;
