### ISSUE TITLE
近期使用 miniprogram-to-uniapp 转换 微信小程序为 uni_app 项目问题总结

### ISSUE THREAD

**Issue by smalike** [zhangdaren/miniprogram-to-uniapp#16]
miniprogram-to-uniapp 转换 uni_app 项目
https://github.com/zhangdaren/miniprogram-to-uniapp

1. 图片资源需要拷贝到 static 目录下（--没有就新建一个，并修改引用路径）
2. scroll-view 组件属性 scrollY 在转换后为 scrolly。（--应当转换为 scroll-y 才能正确显示）
3. t.setData 转换有很多问题。a. 转换丢失后边的代码。 b. 没有被转换（--最好是定义 methods 对象 setData 方法，省去转换带来的问题。
```
setData(obj) {
  const keys = Object.keys(obj);
  keys.forEach((key) => {
    this[key] = obj[key];
  });
},
```
）
4. 转换后 App.vue 方法没有定义到 methods 中（--需要手动创建 methods 对象后拷贝过来）
5. require 上边的函数被去除掉了（--需要找到复制过来）
6. 无法转换 wxs 元素（--重命名 js 文件导入到页面可以解决）
7. 注意 H5 不支持的一些功能 wx.getFileSystemManager 等（--只能删掉这些功能）
8. movable-area 组件出现问题
9. data get、set 处理 （--
```
computed: {
    list: {
        get() {
            return [].concat(e(o.globalData.source[1]), e(o.globalData.source[2]), e(o.globalData.source[3]), e(o.globalData.source[4]));
        },
    },
},
```
）
10. 组件 collectionModal 标签为 <collectionmodal>（--需要修改为 collection-modal）
11. 无法处理 triggerEvent（--修改为$emit 方式）
12. 在处理复杂的三元表达式时容易丢掉东西（--需要从源程序拷贝回来）
13. miniprogram-to-uniapp 组件转换时这里 src/wx2uni/jsHandle.js#86 出现 parent 为 null 的问题（--暂时增加判断容错处理，会有很多不能转换的需要手动更改
```
if (parent) {
    parent.replaceWithMultiple(nodeArr);
}
```
）

参考：
https://ask.dcloud.net.cn/article/35786

**Comment by zhangdaren** [comment]
感谢总结，将尽快修复哈~~

**Comment by zhangdaren** [comment]
10. 组件 collectionModal 标签为 （--需要修改为 collection-modal）
这个是自定义组件吧？

12. 在处理复杂的三元表达式时容易丢掉东西（--需要从源程序拷贝回来）
是否为含setData的三元表达式，还是不含setData的？

13. miniprogram-to-uniapp 组件转换时这里 src/wx2uni/jsHandle.js#86 出现 parent 为 null 的问题（--暂时增加判断容错处理，会有很多不能转换的需要手动更改
与转换setData有关。

**Comment by smalike** [comment]
10. 是一个自定义组件

11. 这个忘记了

什么时候修复啊？

**Comment by zhangdaren** [comment]
今天或明天更新一版，自定义组件那里还是有点小问题。

**Comment by zhangdaren** [comment]
自定义组件按下面方式引用，测试没问题哈~~
<nav-bar2></nav-bar2>
import navBar2 from "../../components/nav-bar2/nav-bar2";

**Comment by zhangdaren** [comment]
已更新v1.0.15，除6.7.8.10小小存疑外，都已经解决。
