### ISSUE TITLE
子组件内使用setData和emit函数报 TypeError: this.$forceUpdate is not a function 错误

### ISSUE THREAD

**Issue by calvinlsy86** [zhangdaren/miniprogram-to-uniapp#174]
### 问题描述？
组件内包含的子组件，在使用this.setData和this.$emit的时候，会报 TypeError: this.$forceUpdate is not a function 错误
<img width="435" alt="image" src="https://github.com/user-attachments/assets/e215bfe6-905c-4d3c-bc30-b1c4806543b5">

### 重现步骤
<u-parent-comp>
       <u-child-comp  @changeType="changeType"/>
</u-parent-comp>

在u-child-comp组件的methods 下创建函数，如

methods: {
     updateData(obj){
           this.setData({obj})
     },
     
     change(type){
          this.$emit('changeType', {
                        detail: {
                            type
                        }
          });
     }
}
### 期望的结果

 在子组件也正常使用setData和this.$emit

**Comment by FreeManFJ** [comment]
我也遇到了

**Comment by calvinlsy86** [comment]
> 我也遇到了

我现在解决了，this指向不明的原因，解决方法：在export default 外部定义一个 let that = this
