### ISSUE TITLE
globalData无法赋值的问题

### ISSUE THREAD

**Issue by jiangmintun123** [zhangdaren/miniprogram-to-uniapp#18]
发现在App.vue里面对globalData赋的值无法储存到globalData里面

**Comment by zhangdaren** [comment]
确实有这个问题，uni-app使用globalData也是不行。

**Comment by zhangdaren** [comment]
最新版v1.0.14已经修复此功能了，请更新使用。
在app.vue里使用this.$options.globalData.xxx的方式来设置数据
