### ISSUE TITLE
1.0.11执行wtu -i "" 命令后，只将文件夹创建了文件未转换，如图

### ISSUE THREAD

**Issue by youyuanyl** [zhangdaren/miniprogram-to-uniapp#19]
![1564045291(1)](https://user-images.githubusercontent.com/36779472/61861237-04fb1200-aefe-11e9-9062-fa6d37a31dda.jpg)
![1564045381(1)](https://user-images.githubusercontent.com/36779472/61861282-193f0f00-aefe-11e9-9fce-02fc7d61695b.jpg)

**Comment by zhangdaren** [comment]
请换v1.0.12试试吧，v1.0.11代码有点问题，今明将更新v1.0.13，修复增加一些功能，敬请关注
