### ISSUE TITLE
模块分析失败：参数名冲突 您可能需要适当的加载程序来处理此文件类型。

### ISSUE THREAD

**Issue by 54huige** [zhangdaren/miniprogram-to-uniapp#20]
15:48:47.612 项目 'hefei_uni' 开始编译...
15:48:50.650  INFO  Starting development server...
15:49:00.296 文件查找失败：'../../wxParse/wxParse.js' at pages\index\index.vue:1173
15:49:00.297 Module parse failed: Argument name clash (10:52)
15:49:00.304 You may need an appropriate loader to handle this file type.
15:49:00.306 |       _vm.scoreHisList !== null
15:49:00.310 |         ? [
15:49:00.315 >             _vm._l(_vm.scoreHisList, function(item, item) {
15:49:00.316 |               return [
15:49:00.326 |                 _c(
15:49:00.327 Module parse failed: Argument name clash (10:55)
15:49:00.334 You may need an appropriate loader to handle this file type.
15:49:00.335 |       _vm.ranListIntegralData !== null
15:49:00.340 |         ? [
15:49:00.341 >             _vm._l(_vm.ranListIntegral, function(item, item) {
15:49:00.347 |               return [
15:49:00.348 |                 _c(
15:49:00.355 Module parse failed: Argument name clash (11:51)
15:49:00.357 You may need an appropriate loader to handle this file type.
15:49:00.366 |       _vm.shopPreSale !== null
15:49:00.367 |         ? [
15:49:00.372 >             _vm._l(_vm.shopPreSale, function(item, item) {
15:49:00.378 |               return [
15:49:00.382 |                 _c(
15:49:00.387 Module parse failed: Argument name clash (123:28)
15:49:00.395 You may need an appropriate loader to handle this file type.
15:49:00.399 |                           _vm._l(item.appraisesAnnex, function(
15:49:00.405 |                             upLoadImg,
15:49:00.411 >                             upLoadImg
15:49:00.415 |                           ) {
15:49:00.420 |                             return [
15:49:00.421 Module parse failed: Argument name clash (1447:52)
15:49:00.430 You may need an appropriate loader to handle this file type.
15:49:00.431 |                                                   function(
15:49:00.436 |                                                     upLoadImg,
15:49:00.437 >                                                     upLoadImg
15:49:00.446 |                                                   ) {
15:49:00.448 |                                                     return [
15:49:00.453 Module parse failed: Argument name clash (326:32)
15:49:00.463 You may need an appropriate loader to handle this file type.
15:49:00.464 |                               _vm._l(userItem.appraisesAnnex, function(
15:49:00.470 |                                 upLoadImg,
15:49:00.471 >                                 upLoadImg
15:49:00.479 |                               ) {
15:49:00.480 |                                 return [

**Comment by 54huige** [comment]
大佬这种情况需要源码给到你 复现一下吗

**Comment by zhangdaren** [comment]
wxParse 是个特例，uni-app对于非pages、static、components等目录里的文件会删除或进行 合并，所以建议转换后，将wxparse手动增加，或者替换uniapp所对应的插件试试。

**Comment by zhangdaren** [comment]
如果有源码也更好，看能不能尽量解决这个问题。

**Comment by 54huige** [comment]
> 如果有源码也更好，看能不能尽量解决这个问题。
我这边解决的话 要先给wxparse删除以及引用 就行了是吧 总麻烦大佬你 这种特例就算了 我能手动解决就行 在转换前去掉这个就行？

**Comment by 54huige** [comment]
> 如果有源码也更好，看能不能尽量解决这个问题。

大佬 我觉得还是给你源码吧 我觉得我们这套源码转换没问题 市场70%应该都不会有问题了

**Comment by zhangdaren** [comment]
> > 如果有源码也更好，看能不能尽量解决这个问题。
> 
> 大佬我觉得还是给你源码吧我觉得我们这套源码转换没问题市场70％应该都不会有问题了

貌似有一套源码，也遇到过这样的问题。

**Comment by zhangdaren** [comment]
大牛，最近经过一个小程序项目的历炼，又填了蛮多坑。
你的小程序经过转换是ok的，唯一就是在授权那里，需要修改一下下。
最新版本：v1.0.24

**Comment by 54huige** [comment]
> 大佬，最近经过一个小程序项目的历炼，又填了蛮多坑。
> 你的小程序经过转换是ok的，唯一就是在授权那里，需要修改一下下。
> 最新版本：v1.0.24

[wx-to-uni-app]: data里没有的变量:    PriceDifference -- Identifier    file: pages\tpls\shop\shop.js
[wx-to-uni-app]: data里没有的变量:    shopFollowStatus -- Identifier    file: pages\tpls\shop\shop.js
[wx-to-uni-app]: data里没有的变量:    searchLetter -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    ciryValue -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    isserchShow -- BooleanLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    selectNearby -- MemberExpression    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    county -- StringLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    condition -- BooleanLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    sectionCity -- StringLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    currentCity -- StringLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    countyList -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    scrollTop -- NumericLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    duration -- NumericLiteral    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    sectionAreaName -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    toastShowLetter -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    scrollTopId -- Identifier    file: pages\tpls\switchcity\switchcity.js
[wx-to-uni-app]: data里没有的变量:    toShopHome -- Identifier    file: pages\tpls\support\support.js
[wx-to-uni-app]: data里没有的变量:    toShopHomeNo -- Identifier    file: pages\tpls\support\support.js
[wx-to-uni-app]: data里没有的变量:    incomeDetails -- MemberExpression    file: pages\distribution\personIRecommend\incomeDetails\incomeDetails.js


这个有什么影响吗 全部红色  麻烦大佬看下  我刚试过

**Comment by zhangdaren** [comment]
> > 大佬，最近经过一个小程序项目的历炼，又填了蛮多坑。
> > 你的小程序经过转换是ok的，唯一就是在授权那里，需要修改一下下。
> > 最新版本：v1.0.24
> 
> [wx-to-uni-app]: data里没有的变量: PriceDifference -- Identifier file: pages\tpls\shop\shop.js
> [wx-to-uni-app]: data里没有的变量: shopFollowStatus -- Identifier file: pages\tpls\shop\shop.js
> [wx-to-uni-app]: data里没有的变量: searchLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: ciryValue -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: isserchShow -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: selectNearby -- MemberExpression file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: county -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: condition -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: sectionCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: currentCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: countyList -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: scrollTop -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: duration -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: sectionAreaName -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: toastShowLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: scrollTopId -- Identifier file: pages\tpls\switchcity\switchcity.js
> [wx-to-uni-app]: data里没有的变量: toShopHome -- Identifier file: pages\tpls\support\support.js
> [wx-to-uni-app]: data里没有的变量: toShopHomeNo -- Identifier file: pages\tpls\support\support.js
> [wx-to-uni-app]: data里没有的变量: incomeDetails -- MemberExpression file: pages\distribution\personIRecommend\incomeDetails\incomeDetails.js
> 
> 这个有什么影响吗 全部红色 麻烦大佬看下 我刚试过

这个不影响哈，只是我的运行日志而已，下版我改成绿色或去掉。

**Comment by 54huige** [comment]
> > > 大佬，最近经过一个小程序项目的历炼，又填了蛮多坑。
> > > 你的小程序经过转换是ok的，唯一就是在授权那里，需要修改一下下。
> > > 最新版本：v1.0.24
> > 
> > 
> > [wx-to-uni-app]: data里没有的变量: PriceDifference -- Identifier file: pages\tpls\shop\shop.js
> > [wx-to-uni-app]: data里没有的变量: shopFollowStatus -- Identifier file: pages\tpls\shop\shop.js
> > [wx-to-uni-app]: data里没有的变量: searchLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: ciryValue -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: isserchShow -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: selectNearby -- MemberExpression file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: county -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: condition -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: sectionCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: currentCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: countyList -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: scrollTop -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: duration -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: sectionAreaName -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: toastShowLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: scrollTopId -- Identifier file: pages\tpls\switchcity\switchcity.js
> > [wx-to-uni-app]: data里没有的变量: toShopHome -- Identifier file: pages\tpls\support\support.js
> > [wx-to-uni-app]: data里没有的变量: toShopHomeNo -- Identifier file: pages\tpls\support\support.js
> > [wx-to-uni-app]: data里没有的变量: incomeDetails -- MemberExpression file: pages\distribution\personIRecommend\incomeDetails\incomeDetails.js
> > 这个有什么影响吗 全部红色 麻烦大佬看下 我刚试过
> 
> 这个不影响哈，只是我的运行日志而已，下版我改成绿色或去掉。
> 这个日志是表示，页面里面没有在data下面定义变量，就使用了setData()来设置，在小程序能通过，但vue里是不支持的。
> 所以我做了些微小的努力，将setData()里的变量都收集起来，然后跟data里的变量对比，没有就添加上。


辛苦了大佬  不过我这边运行不起来 说是变量冲突
18:26:43.280  INFO  Starting development server...
18:27:15.949 Module parse failed: Argument name clash (10:52)
18:27:15.949 You may need an appropriate loader to handle this file type.
18:27:15.953 |       _vm.scoreHisList !== null
18:27:15.953 |         ? [
18:27:15.957 >             _vm._l(_vm.scoreHisList, function(item, item) {
18:27:15.957 |               return [
18:27:15.963 |                 _c(
18:27:15.964 Module parse failed: Argument name clash (10:55)
18:27:15.968 You may need an appropriate loader to handle this file type.
18:27:15.969 |       _vm.ranListIntegralData !== null
18:27:15.978 |         ? [
18:27:15.978 >             _vm._l(_vm.ranListIntegral, function(item, item) {
18:27:15.985 |               return [
18:27:15.985 |                 _c(
18:27:15.989 Module parse failed: Argument name clash (11:51)
18:27:15.990 You may need an appropriate loader to handle this file type.
18:27:15.997 |       _vm.shopPreSale !== null
18:27:15.997 |         ? [
18:27:16.004 >             _vm._l(_vm.shopPreSale, function(item, item) {
18:27:16.006 |               return [
18:27:16.013 |                 _c(
18:27:16.013 Module parse failed: Argument name clash (125:28)
18:27:16.018 You may need an appropriate loader to handle this file type.
18:27:16.018 |                           _vm._l(item.appraisesAnnex, function(
18:27:16.028 |                             upLoadImg,
18:27:16.028 >                             upLoadImg
18:27:16.035 |                           ) {
18:27:16.036 |                             return [
18:27:16.044 Module parse failed: Argument name clash (1460:52)
18:27:16.045 You may need an appropriate loader to handle this file type.
18:27:16.050 |                                                   function(
18:27:16.051 |                                                     upLoadImg,
18:27:16.060 >                                                     upLoadImg
18:27:16.060 |                                                   ) {
18:27:16.069 |                                                     return [
18:27:16.069 Module parse failed: Argument name clash (326:32)
18:27:16.078 You may need an appropriate loader to handle this file type.
18:27:16.078 |                               _vm._l(userItem.appraisesAnnex, function(
18:27:16.084 |                                 upLoadImg,
18:27:16.085 >                                 upLoadImg
18:27:16.093 |                               ) {
18:27:16.094 |                                 return [

**Comment by zhangdaren** [comment]
> > > > 大佬，最近经过一个小程序项目的历炼，又填了蛮多坑。
> > > > 你的小程序经过转换是ok的，唯一就是在授权那里，需要修改一下下。
> > > > 最新版本：v1.0.24
> > > 
> > > 
> > > [wx-to-uni-app]: data里没有的变量: PriceDifference -- Identifier file: pages\tpls\shop\shop.js
> > > [wx-to-uni-app]: data里没有的变量: shopFollowStatus -- Identifier file: pages\tpls\shop\shop.js
> > > [wx-to-uni-app]: data里没有的变量: searchLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: ciryValue -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: isserchShow -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: selectNearby -- MemberExpression file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: county -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: condition -- BooleanLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: sectionCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: currentCity -- StringLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: countyList -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: scrollTop -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: duration -- NumericLiteral file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: sectionAreaName -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: toastShowLetter -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: scrollTopId -- Identifier file: pages\tpls\switchcity\switchcity.js
> > > [wx-to-uni-app]: data里没有的变量: toShopHome -- Identifier file: pages\tpls\support\support.js
> > > [wx-to-uni-app]: data里没有的变量: toShopHomeNo -- Identifier file: pages\tpls\support\support.js
> > > [wx-to-uni-app]: data里没有的变量: incomeDetails -- MemberExpression file: pages\distribution\personIRecommend\incomeDetails\incomeDetails.js
> > > 这个有什么影响吗 全部红色 麻烦大佬看下 我刚试过
> > 
> > 
> > 这个不影响哈，只是我的运行日志而已，下版我改成绿色或去掉。
> > 这个日志是表示，页面里面没有在data下面定义变量，就使用了setData()来设置，在小程序能通过，但vue里是不支持的。
> > 所以我做了些微小的努力，将setData()里的变量都收集起来，然后跟data里的变量对比，没有就添加上。
> 
> 辛苦了大佬 不过我这边运行不起来 说是变量冲突
> 18:26:43.280 INFO Starting development server...
> 18:27:15.949 Module parse failed: Argument name clash (10:52)
> 18:27:15.949 You may need an appropriate loader to handle this file type.
> 18:27:15.953 | _vm.scoreHisList !== null
> 18:27:15.953 | ? [
> 18:27:15.957 > _vm._l(_vm.scoreHisList, function(item, item) {
> 18:27:15.957 | return [
> 18:27:15.963 | _c(
> 18:27:15.964 Module parse failed: Argument name clash (10:55)
> 18:27:15.968 You may need an appropriate loader to handle this file type.
> 18:27:15.969 | _vm.ranListIntegralData !== null
> 18:27:15.978 | ? [
> 18:27:15.978 > _vm._l(_vm.ranListIntegral, function(item, item) {
> 18:27:15.985 | return [
> 18:27:15.985 | _c(
> 18:27:15.989 Module parse failed: Argument name clash (11:51)
> 18:27:15.990 You may need an appropriate loader to handle this file type.
> 18:27:15.997 | _vm.shopPreSale !== null
> 18:27:15.997 | ? [
> 18:27:16.004 > _vm._l(_vm.shopPreSale, function(item, item) {
> 18:27:16.006 | return [
> 18:27:16.013 | _c(
> 18:27:16.013 Module parse failed: Argument name clash (125:28)
> 18:27:16.018 You may need an appropriate loader to handle this file type.
> 18:27:16.018 | _vm._l(item.appraisesAnnex, function(
> 18:27:16.028 | upLoadImg,
> 18:27:16.028 > upLoadImg
> 18:27:16.035 | ) {
> 18:27:16.036 | return [
> 18:27:16.044 Module parse failed: Argument name clash (1460:52)
> 18:27:16.045 You may need an appropriate loader to handle this file type.
> 18:27:16.050 | function(
> 18:27:16.051 | upLoadImg,
> 18:27:16.060 > upLoadImg
> 18:27:16.060 | ) {
> 18:27:16.069 | return [
> 18:27:16.069 Module parse failed: Argument name clash (326:32)
> 18:27:16.078 You may need an appropriate loader to handle this file type.
> 18:27:16.078 | _vm._l(userItem.appraisesAnnex, function(
> 18:27:16.084 | upLoadImg,
> 18:27:16.085 > upLoadImg
> 18:27:16.093 | ) {
> 18:27:16.094 | return [

还是原来那一份代码吗？我这没见到这个这个错误哇
