### ISSUE TITLE
近期转换小程序为 uni 项目出现的问题

### ISSUE THREAD

**Issue by smalike** [zhangdaren/miniprogram-to-uniapp#22]
- 因为 key 为 item*this 的问题导致 for 转换失败：v-for="(item, item*this) in leave" :key="item*this" --- <view class="item" v-for="(item, item*this) in leave" :key="item*this" wx:for-index="idx">

- 属性名与方法名重复的问题

- 属性未定义的问题

- hover-start-time、hover-stay-time 需要转换为 number 类型

- 为转换 import 方式 https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html

- 需要转换字符串拼接为 `` 方式      <view :style="'height: ' + sideSize - 5 + 'px; width:100%;'">

- class 丢失、没有被转换  class='{{toolTip.type==="timing" ? "toolTip timing" : "toolTip"}}'（修改为 :class='toolTip.type==="timing" ? "toolTip timing" : "toolTip"'）

- catchtap 事件无法转换（替换为 v-on:click.stop）

- e.currentTarget.dataset  值默认为字符类型的问题（使用 + 转换为 Number）

另外此次转换所有样式都没有提出来，原因可能是在转换时出现了 image 资源找不到的错误引起。错误信息如下：
`SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group
    at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18)
    at new Promise (<anonymous>)
    at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19)
    at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Convert app.vue success!
write /Users/jianglijia/Downloads/sudoLite-master_uni/pages.json success!
write /Users/jianglijia/Downloads/sudoLite-master_uni/manifest.json success!
Convert index.vue success!
Convert index.vue success!
write /Users/jianglijia/Downloads/sudoLite-master_uni/main.js success!
Convert index.vue success!
Convert index.vue success!
Convert loading.vue success!
Convert index.vue success!`

**Comment by zhangdaren** [comment]
大佬厉害~~

因为 key 为 itemthis 的问题导致 for 转换失败：v-for="(item, itemthis) in leave" :key="item*this" ---
/// 源码是：wx:for="item in leave" wx:key="itemthis" ？

属性未定义的问题
///这个能具体说说吗？

为转换 import 方式 https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html
///这个确实有。

需要转换字符串拼接为 `` 方式
///这个有示例代码吗？

**Comment by myfengstyle** [comment]
什么时候能修复呢

**Comment by zhangdaren** [comment]
> 什么时候能修复呢

周末出一版，解决大部分问题，，import wxml这个问题，还在研究，涉及地方比较多。

**Comment by zhangdaren** [comment]
> * 因为 key 为 item_this 的问题导致 for 转换失败：v-for="(item, item_this) in leave" :key="item*this" ---
> * 属性名与方法名重复的问题
> * 属性未定义的问题
> * hover-start-time、hover-stay-time 需要转换为 number 类型
> * 为转换 import 方式 https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html
> * 需要转换字符串拼接为 `` 方式
> * class 丢失、没有被转换  class='{{toolTip.type==="timing" ? "toolTip timing" : "toolTip"}}'（修改为 :class='toolTip.type==="timing" ? "toolTip timing" : "toolTip"'）
> * catchtap 事件无法转换（替换为 v-on:click.stop）
> * e.currentTarget.dataset  值默认为字符类型的问题（使用 + 转换为 Number）
> 
> 另外此次转换所有样式都没有提出来，原因可能是在转换时出现了 image 资源找不到的错误引起。错误信息如下：
> `SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) SyntaxError: Invalid regular expression: /url\(('|")(?<filePath>.*?).(?<extname>jpg|jpeg|gif|svg|png)('|")\)/: Invalid group at Promise (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:47:18) at new Promise (<anonymous>) at cssHandle (/Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/cssHandle.js:18:19) at /Users/jianglijia/.nvm/versions/node/v8.15.1/lib/node_modules/miniprogram-to-uniapp/src/index.js:288:27 at <anonymous> at process._tickCallback (internal/process/next_tick.js:189:7) Convert app.vue success! write /Users/jianglijia/Downloads/sudoLite-master_uni/pages.json success! write /Users/jianglijia/Downloads/sudoLite-master_uni/manifest.json success! Convert index.vue success! Convert index.vue success! write /Users/jianglijia/Downloads/sudoLite-master_uni/main.js success! Convert index.vue success! Convert index.vue success! Convert loading.vue success! Convert index.vue success!`

请问可以提供示例代码嘛？

**Comment by zhangdaren** [comment]
v1.0.16已更新，解决了如下问题
1.wx:key="*this" 或wx:key="*item" 的问题
2.import *.wxml解决了部分，data参数需要为key：value对象的形式
3.class转换修复
4.catchtap 事件无法转换
等等

上述未有测试代码，限于时间将尽量于下版解决。

**Comment by zhangdaren** [comment]
为转换 import 方式 https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html

今天研究了一下，本来代码都已经写好，能够简单转换过去，实际运行还是有问题。
wxs语法略微有点不同于js，这个倒是好说，难点在于template模板里的变量必须要在data里面事先声明才能使用。
需要分析wxs文件然后把变量和function融合进来，有点头疼……

**Comment by myfengstyle** [comment]
先更新一下啊

**Comment by zhangdaren** [comment]
> 先更新一下啊

wxs这部分吗？

**Comment by zhangdaren** [comment]
hover-start-time、hover-stay-time 需要转换为 number 类型
// 看了一下文档是一样的哇~

e.currentTarget.dataset 值默认为字符类型的问题（使用 + 转换为 Number）
//这个应该是一个对象吧

**Comment by zhangdaren** [comment]
已更新v1.0.18，解决wxs文件的转换问题以及一些bug。
wxs转js的语法转换，下一版更新。

**Comment by zhangdaren** [comment]
> 已更新v1.0.18，解决wxs文件的转换问题以及一些bug。
> wxs转js的语法转换，也已解决。

**Comment by zhangdaren** [comment]
v1.0.21，增加-w命令，即表示转换wxs文件，不加就表示不进行转换wxs文件，因为现在uni-app在app和小程序上已经支持wxs，即将在h5上也将支持，所以默认不进行转换了。
