### ISSUE TITLE
UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by jhmei** [zhangdaren/miniprogram-to-uniapp#23]
(node:14148) UnhandledPromiseRejectionWarning: error： 这个目录D:\xxx\xxx-miniprogram-xxx应该不是小程序的目录
(node:14148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 1.0.17版本一直爆这个错
@zhangdaren

**Comment by zhangdaren** [comment]
该目录下面是否存在project.config.json文件？目前是根据是否含此文件来判断是否为小程序项目目录。

**Comment by zhangdaren** [comment]
v1.0.20已解决了这个问题，不存在project.config.json也可进行转换。

**Comment by jhmei** [comment]
very nice，灰常感谢
