### ISSUE TITLE
转化提示的错误，有的生成不了manifest.json文件

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#24]
SyntaxError: Invalid regular expression: /url\(['"](?<filePath>.*?)\.(?<extname>jpg|jpeg|gif|svg|png)['"]\)/: Invalid group
    at Promise (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
    at new Promise (<anonymous>)
    at cssHandle (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
    at C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:345:27
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
SyntaxError: Invalid regular expression: /url\(['"](?<filePath>.*?)\.(?<extname>jpg|jpeg|gif|svg|png)['"]\)/: Invalid group
    at Promise (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
    at new Promise (<anonymous>)
    at cssHandle (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
    at C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:345:27
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
SyntaxError: Invalid regular expression: /url\(['"](?<filePath>.*?)\.(?<extname>jpg|jpeg|gif|svg|png)['"]\)/: Invalid group
    at Promise (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
    at new Promise (<anonymous>)
    at cssHandle (C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
    at C:\Users\zhangwork\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:345:27

**Comment by myfengstyle** [comment]
语法错误: D:\xcx\fanqie_uni\main.js: Unexpected token (5:16)
10:03:56.087   3 | import App from './App';

import Vue from 'vue';
import App from './App';

import adContent.vue from "../../components/adContent.vue.vue";
Vue.component('adcontent.vue.vue', adContent.vue);

import qdTCtool.vue from "../../components/qdTCtool.vue.vue";
Vue.component('qdtctool.vue.vue', qdTCtool.vue);

import headrTools.vue from "../../components/headrTools.vue.vue";
Vue.component('headrtools.vue.vue', headrTools.vue);

import cjItem.vue from "../../components/cjItem.vue.vue";
Vue.component('cjitem.vue.vue', cjItem.vue);

import redPacket.vue from "../../components/redPacket.vue.vue";
Vue.component('redpacket.vue.vue', redPacket.vue);

import allJoinPerson.vue from "../../pages/allJoinPerson/allJoinPerson.vue.vue";
Vue.component('alljoinperson.vue.vue', allJoinPerson.vue);

import allZjList.vue from "../../pages/allZjList/allZjList.vue.vue";
Vue.component('allzjlist.vue.vue', allZjList.vue);

import allZjList1.vue from "../../pages/allZjList1/allZjList1.vue.vue";
Vue.component('allzjlist1.vue.vue', allZjList1.vue);

import bsdh.vue from "../../pages/bsdh/bsdh.vue.vue";
Vue.component('bsdh.vue.vue', bsdh.vue);

import cjzn.vue from "../../pages/cjzn/cjzn.vue.vue";
Vue.component('cjzn.vue.vue', cjzn.vue);

import creatShareImage.vue from "../../pages/creatShareImage/creatShareImage.vue.vue";
Vue.component('creatshareimage.vue.vue', creatShareImage.vue);

import creatZjImage.vue from "../../pages/creatZjImage/creatZjImage.vue.vue";
Vue.component('creatzjimage.vue.vue', creatZjImage.vue);

import cycj.vue from "../../pages/cycj/cycj.vue.vue";
Vue.component('cycj.vue.vue', cycj.vue);

import exchangeInfo.vue from "../../pages/exchangeInfo/exchangeInfo.vue.vue";
Vue.component('exchangeinfo.vue.vue', exchangeInfo.vue);

import exchangeList.vue from "../../pages/exchangeList/exchangeList.vue.vue";
Vue.component('exchangelist.vue.vue', exchangeList.vue);

import exchangePeople.vue from "../../pages/exchangePeople/exchangePeople.vue.vue";
Vue.component('exchangepeople.vue.vue', exchangePeople.vue);

import exchangeSuccess.vue from "../../pages/exchangeSuccess/exchangeSuccess.vue.vue";
Vue.component('exchangesuccess.vue.vue', exchangeSuccess.vue);

import fqcj.vue from "../../pages/fqcj/fqcj.vue.vue";
Vue.component('fqcj.vue.vue', fqcj.vue);

import gatherHoney.vue from "../../pages/gatherHoney/gatherHoney.vue.vue";
Vue.component('gatherhoney.vue.vue', gatherHoney.vue);

import friendHelp.vue from "../../pages/friendHelp/friendHelp.vue.vue";
Vue.component('friendhelp.vue.vue', friendHelp.vue);

import indexList.vue from "../../pages/indexList/indexList.vue.vue";
Vue.component('indexlist.vue.vue', indexList.vue);

import invRank.vue from "../../pages/invRank/invRank.vue.vue";
Vue.component('invrank.vue.vue', invRank.vue);

import mfmx.vue from "../../pages/mfmx/mfmx.vue.vue";
Vue.component('mfmx.vue.vue', mfmx.vue);

import itemInfo.vue from "../../pages/itemInfo/itemInfo.vue.vue";
Vue.component('iteminfo.vue.vue', itemInfo.vue);

import my.vue from "../../pages/my/my.vue.vue";
Vue.component('my.vue.vue', my.vue);

import myCode.vue from "../../pages/myCode/myCode.vue.vue";
Vue.component('mycode.vue.vue', myCode.vue);

import myInvPerson.vue from "../../pages/myInvPerson/myInvPerson.vue.vue";
Vue.component('myinvperson.vue.vue', myInvPerson.vue);

import myZSInvCodee.vue from "../../pages/myZSInvCodee/myZSInvCodee.vue.vue";
Vue.component('myzsinvcodee.vue.vue', myZSInvCodee.vue);

import newCjItem.vue from "../../pages/newCjItem/newCjItem.vue.vue";
Vue.component('newcjitem.vue.vue', newCjItem.vue);

import openRPList.vue from "../../pages/openRPList/openRPList.vue.vue";
Vue.component('openrplist.vue.vue', openRPList.vue);

import openRedPacket.vue from "../../pages/openRedPacket/openRedPacket.vue.vue";
Vue.component('openredpacket.vue.vue', openRedPacket.vue);

import pCode.vue from "../../pages/pCode/pCode.vue.vue";
Vue.component('pcode.vue.vue', pCode.vue);

import pInvCode.vue from "../../pages/pInvCode/pInvCode.vue.vue";
Vue.component('pinvcode.vue.vue', pInvCode.vue);

import renzhrengList.vue from "../../pages/renzhengList/renzhrengList.vue.vue";
Vue.component('renzhrenglist.vue.vue', renzhrengList.vue);

import settingCj.vue from "../../pages/settingCj/settingCj.vue.vue";
Vue.component('settingcj.vue.vue', settingCj.vue);

import settingCjInfo.vue from "../../pages/settingCjInfo/settingCjInfo.vue.vue";
Vue.component('settingcjinfo.vue.vue', settingCjInfo.vue);

import settingCjOther.vue from "../../pages/settingCjOther/settingCjOther.vue.vue";
Vue.component('settingcjother.vue.vue', settingCjOther.vue);

import settingCjSuccess.vue from "../../pages/settingCjSuccess/settingCjSuccess.vue.vue";
Vue.component('settingcjsuccess.vue.vue', settingCjSuccess.vue);

import tx.vue from "../../pages/tx/tx.vue.vue";
Vue.component('tx.vue.vue', tx.vue);

import zjjl.vue from "../../pages/zjjl/zjjl.vue.vue";
Vue.component('zjjl.vue.vue', zjjl.vue);

import zjpinfo.vue from "../../pages/zjpinfo/zjpinfo.vue.vue";
Vue.component('zjpinfo.vue.vue', zjpinfo.vue);

Vue.config.productionTip = false;

App.mpType = 'app';

const app = new Vue({
    ...App
});
app.$mount();

**Comment by zhangdaren** [comment]
收到，第一个似乎是文件没有后缀名？

**Comment by zhangdaren** [comment]
第一个应该是node的版本不够新吧？我看我换一种写法。
