### ISSUE TITLE
生成不了manifest.json和page.json文件

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#25]
wxml漏网之鱼: --> src="{{isNightMode?'/images/voice_anim_1_night.gif':'/images/voice_anim_1.gif'}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
wxml漏网之鱼: --> src="{{iconBgPath}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
wxml漏网之鱼: --> src="{{iconPath}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
wxml漏网之鱼: --> src="{{currentMusicId==noiseItem.id?noiseItem.cover_miniapp_white:noiseItem.cover_miniapp_black}}"，所在文件：components\noise-item\noise-item.wxml
wxml漏网之鱼: --> src="{{item.prepare_icon}}"，所在文件：components\sleep-breath-item\sleep-breath-item.wxml
wxml漏网之鱼: --> src="{{item.prepare_icon}}"，所在文件：components\sleep-breath-tips\sleep-breath-tips.wxml
wxml漏网之鱼: --> src="{{item.resurl}}"，所在文件：components\voice-item\voice-item.wxml
wxml漏网之鱼: --> src="{{currentMusic.cover_miniapp_big}}"，所在文件：pages\main\main.wxml
wxml漏网之鱼: --> src="/images/{{isMusicPlaying?'stop.png':'play.png'}}"，所在文件：pages\main\main.wxml
wxml漏网之鱼: --> src="{{item.recommend_type}}"，所在文件：pages\ad-miniapp\ad-miniapp.wxml
wxml漏网之鱼: --> src="{{item.recommend_logo}}"，所在文件：pages\ad-miniapp\ad-miniapp.wxml
wxml漏网之鱼: --> src="{{sleepBreath.prepare_icon}}"，所在文件：pages\sleep-breath-detail\sleep-breath-detail.wxml
wxml漏网之鱼: --> src="https://res.psy-1.com/cosleep/sleep/prepare/breath_bg001-aBAlOH0iUcL85nkynsvp.png"，所在文件：pages\test\test.wxml
wxml漏网之鱼: --> src="{{currentMusic.resurl}}"，所在文件：pages\voice\voice.wxml
wxml漏网之鱼: --> src="{{thumb}}"，所在文件：vendor\vant\card\index.wxml
wxml漏网之鱼: --> src="{{name}}"，所在文件：vendor\vant\icon\index.wxml
wxml漏网之鱼: --> src="{{leftIcon}}"，所在文件：vendor\vant\notice-bar\index.wxml
SyntaxError: Invalid regular expression: /url\(['"](?<filePath>.*?)\.(?<extname>jpg|jpeg|gif|svg|png)['"]\)/: Invalid group
    at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
    at new Promise (<anonymous>)
    at cssHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:412:28
    at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:428:7)
    at new Promise (<anonymous>)
    at filesHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:264:16)
    at traverseFolder (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:531:3)
    at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)
    at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)
SyntaxError: Invalid regular expression: /url\(['"](?<filePath>.*?)\.(?<extname>jpg|jpeg|gif|svg|png)['"]\)/: Invalid group
    at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
    at new Promise (<anonymous>)
    at cssHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:412:28
    at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:428:7)
    at new Promise (<anonymous>)
    at filesHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:264:16)
    at traverseFolder (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:531:3)
    at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)

**Comment by myfengstyle** [comment]
(node:7924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): TypeError: Cannot read property 'body' of undefined
(node:7924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhangdaren** [comment]
> (node:7924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): TypeError: Cannot read property 'body' of undefined
> (node:7924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

大佬，这个方便提供一下源代码嘛？

**Comment by zhangdaren** [comment]
> wxml漏网之鱼: --> src="{{isNightMode?'/images/voice_anim_1_night.gif':'/images/voice_anim_1.gif'}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
> wxml漏网之鱼: --> src="{{iconBgPath}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
> wxml漏网之鱼: --> src="{{iconPath}}"，所在文件：components\ai-voice-recognition\ai-voice-recognition.wxml
> wxml漏网之鱼: --> src="{{currentMusicId==noiseItem.id?noiseItem.cover_miniapp_white:noiseItem.cover_miniapp_black}}"，所在文件：components\noise-item\noise-item.wxml
> wxml漏网之鱼: --> src="{{item.prepare_icon}}"，所在文件：components\sleep-breath-item\sleep-breath-item.wxml
> wxml漏网之鱼: --> src="{{item.prepare_icon}}"，所在文件：components\sleep-breath-tips\sleep-breath-tips.wxml
> wxml漏网之鱼: --> src="{{item.resurl}}"，所在文件：components\voice-item\voice-item.wxml
> wxml漏网之鱼: --> src="{{currentMusic.cover_miniapp_big}}"，所在文件：pages\main\main.wxml
> wxml漏网之鱼: --> src="/images/{{isMusicPlaying?'stop.png':'play.png'}}"，所在文件：pages\main\main.wxml
> wxml漏网之鱼: --> src="{{item.recommend_type}}"，所在文件：pages\ad-miniapp\ad-miniapp.wxml
> wxml漏网之鱼: --> src="{{item.recommend_logo}}"，所在文件：pages\ad-miniapp\ad-miniapp.wxml
> wxml漏网之鱼: --> src="{{sleepBreath.prepare_icon}}"，所在文件：pages\sleep-breath-detail\sleep-breath-detail.wxml
> wxml漏网之鱼: --> src="[https://res.psy-1.com/cosleep/sleep/prepare/breath_bg001-aBAlOH0iUcL85nkynsvp.png"，所在文件：pages\test\test.wxml](https://res.psy-1.com/cosleep/sleep/prepare/breath_bg001-aBAlOH0iUcL85nkynsvp.png%22%EF%BC%8C%E6%89%80%E5%9C%A8%E6%96%87%E4%BB%B6%EF%BC%9Apages%5Ctest%5Ctest.wxml)
> wxml漏网之鱼: --> src="{{currentMusic.resurl}}"，所在文件：pages\voice\voice.wxml
> wxml漏网之鱼: --> src="{{thumb}}"，所在文件：vendor\vant\card\index.wxml
> wxml漏网之鱼: --> src="{{name}}"，所在文件：vendor\vant\icon\index.wxml
> wxml漏网之鱼: --> src="{{leftIcon}}"，所在文件：vendor\vant\notice-bar\index.wxml
> SyntaxError: Invalid regular expression: /url(['"](?%3CfilePath%3E.*?).(?jpg|jpeg|gif|svg|png)['"])/: Invalid group
> at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
> at new Promise ()
> at cssHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
> at C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:412:28
> at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:428:7)
> at new Promise ()
> at filesHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:264:16)
> at traverseFolder (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:531:3)
> at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)
> at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)
> SyntaxError: Invalid regular expression: /url(['"](?%3CfilePath%3E.*?).(?jpg|jpeg|gif|svg|png)['"])/: Invalid group
> at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:52:18)
> at new Promise ()
> at cssHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\wx2uni\cssHandle.js:21:19)
> at C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:412:28
> at Promise (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:428:7)
> at new Promise ()
> at filesHandle (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:264:16)
> at traverseFolder (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:531:3)
> at checkEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\miniprogram-to-uniapp\src\index.js:106:31)

看到"wxml漏网之鱼"，意味着您需要手动调整对应代码，表示image标签的src属性是动态变化的，工具还无法做到100%转换，需要手动修改为相对/static目录的路径


SyntaxError: Invalid regular expression: /url(['"](?%3CfilePath%3E.*?).(?jpg|jpeg|gif|svg|png)['"])/: Invalid group

这个错误，等会更新一个版本即可，应该是node的版本不是新版，有些正则的语法不支持导致的。

**Comment by myfengstyle** [comment]
链接: https://pan.baidu.com/s/1oODS448ZBx5dPHzctaYPeQ 提取码: mxfe 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by myfengstyle** [comment]
(node:38856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
nodejs版本：v10.16.3 提示此错误生成不了manifest.json和page.json文件

**Comment by zhangdaren** [comment]
SyntaxError: Invalid regular expression: /url('".(?jpg|jpeg|gif|svg|png)['"])/: Invalid group

这个我这里用你的源码倒是没出现过哇

已更新v1.0.20，除上面的问题没出现外，都已解决。

**Comment by myfengstyle** [comment]
好的谢谢还没更新吗

**Comment by zhangdaren** [comment]
客气，已经更新啦~~   运行 npm update miniprogram-to-uniapp -g 更新试试 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "fengstyle"<notifications@github.com>; 
发送时间: 2019年8月24日(星期六) 晚上8:14
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 生成不了manifest.json和page.json文件 (#25)




好的谢谢还没更新吗
 
&mdash;

**Comment by zhangdaren** [comment]
漏网之鱼这个问题，可以尝试新版v1.0.21，增加了-c，uni-app cli模式，生成vue项目，可以完美解决这个问题。

使用命令：
`wtu -i "小程序项目路径" -c`

**Comment by yulangchao** [comment]
提示此错误生成不了manifest.json和page.json文件

**Comment by zhangdaren** [comment]
> 提示此错误生成不了manifest.json和page.json文件

现在版本还有这个问题嘛？
