### ISSUE TITLE
最好把未转换成功的记录单独导出成文件一并放在转化后目录，方便查找

### ISSUE THREAD

**Issue by xiaoful** [zhangdaren/miniprogram-to-uniapp#26]
最好把未转换成功的单独导出成文件一并放在转化后目录，方便查找

**Comment by zhangdaren** [comment]
现在的版本还会有未转换成功嘛？
除了wxparse

**Comment by xiaoful** [comment]
有一些"image漏网之鱼"

**Comment by xiaoful** [comment]
在转化日志里面看，不够直观，夹杂其他信息，可以考虑把这些有用信息统一在一起

**Comment by zhangdaren** [comment]
> 有一些"image漏网之鱼"

你提的意见蛮好的，一直没弄日志，我看增加上。
漏网之鱼这个已经解决了，通过生成vue项目的形式来实现的，今天更新版本后，支持生成两种项目形式，hbx和vue项目
