### ISSUE TITLE
vant weapp  必须更换ui组件吗？

### ISSUE THREAD

**Issue by tangShaoYuA** [zhangdaren/miniprogram-to-uniapp#32]

**Comment by zhangdaren** [comment]
尝试看看是否能转换正常？不然还是建议寻找替代的，或者看看插件市场是否有作者将该组件转换为uni-app版本了，否则盘根错结，还是头大。

**Comment by zhangdaren** [comment]
经过研究，由于VantComponent({})与小程序结构差异较大，且组件内部强耦合，加上uni-app现在不支持 ```:class="bem('xxx')"```这种语法，虽然可以勉强做出一版来。但是考虑到vant后续更新，需要花费的力气不少，建议手动更换替换。  

目前插件市场已有的vant示例，也仅能支持在小程序和app，其他平台不支持。

ps：不知道有需要vant开发的量有多大？如果仅需要支持小程序和app倒是可以弄的。

**Comment by tangShaoYuA** [comment]
对于微信小程序组件关系relation，请问有如何适配到支付宝小程序组件的思路吗？vant-weapp中有大量使用组件关系relation。 @zhangdaren

**Comment by zhangdaren** [comment]
现在最新v1.0.58可以支持转换使用了vant的项目，，但目前仅支持v3的app和H5，其它平台不支持（只能等后续uni支持）

**Comment by zhangdaren** [comment]
v1.0.59  支持自动识别转换vant项目。
