### ISSUE TITLE
<view :class="'page-container ' + (isNightMode?'night-mode':'') + ' ' + (isBigFontMode?'big-font-mode':'')">运行报错

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#33]
<view :class="'page-container ' + (isNightMode?'night-mode':'') + ' ' + (isBigFontMode?'big-font-mode':'')">
转换后变成
<view :class="'page-container ' + (isNightMode?'night-mode':'') + ' ' + (isBigFontMode?'big-font-mode':'')">

运行保存

**Comment by myfengstyle** [comment]
转化前
`<view :class="'page-container ' + (isNightMode?'night-mode':'') + ' ' + (isBigFontMode?'big-font-mode':'')">`

**Comment by myfengstyle** [comment]
转化后变成`<view :class="'page-container ' + (isNightMode?'night-mode':'') + ' ' + (isBigFontMode?'big-font-mode':'')">`

**Comment by myfengstyle** [comment]
转化前是
`<view class="page-container {{isNightMode?'night-mode':''}} {{isBigFontMode?'big-font-mode':''}}">`

**Comment by zhangdaren** [comment]
请问一下是报什么错？  测试没问题哇
