### ISSUE TITLE
style属性转化出错

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#34]
原来的是
style="background-image: url('{{item.recommend_cover}}');"
转换后
:style="'background-image: url('' + item.recommend_cover + '');'"
报错了

**Comment by myfengstyle** [comment]
应该转化成
v-bind:style="{ backgroundImage:'url（'+ item.recommend_cover +'）'}"
吧

**Comment by zhangdaren** [comment]
感谢，最新版v1.0.25已经修复了这个问题哈

**Comment by myfengstyle** [comment]
新版转化还是不对，style方法错误还是很多哦

**Comment by zhangdaren** [comment]
能给出示例嘛？ 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "fengstyle"<notifications@github.com>; 
发送时间: 2019年10月8日(星期二) 晚上11:22
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] style属性转化出错 (#34)




新版转化还是不对，style方法错误还是很多哦

**Comment by zhangdaren** [comment]
> 应该转化成
> v-bind:style="{ backgroundImage:'url（'+ item.recommend_cover +'）'}"
> 吧

下面代码，在app，h5，小程序里都能运行成功。
···<view :style="'background-image: url(' + abc + ');'">test</view>···

**Comment by chenzefeng09** [comment]
这个你可以试下写多于一个的属性，就看出问题了，因为转换为这样
![image](https://user-images.githubusercontent.com/7556537/82808685-0bab3a80-9ebd-11ea-8b87-c0598677ad34.png)
注意看属性之间是没有分号的，如问题 #71 所说

@zhangdaren

**Comment by zhangdaren** [comment]
> 这个你可以试下写多于一个的属性，就看出问题了，因为转换为这样
> ![image](https://user-images.githubusercontent.com/7556537/82808685-0bab3a80-9ebd-11ea-8b87-c0598677ad34.png)
> 注意看属性之间是没有分号的，如问题 #71 所说
> 
> @zhangdaren

经测：
转换前：
```
<text class="user-motto" style="color:{{color}};font-size:{{size}};background: url({{url}});">{{title}}</text>
data:{
		color: "#F00",
		size: "66rpx",
		url: "xxx.png",
		title: "这是标题！！！"
}
```

转换后：
```
  <text class="user-motto" :style="'color:' + color + ';font-size:' + size + ';background: url(' + url + ');'">{{title}}</text>
data:{
		color: "#F00",
		size: "66rpx",
		url: "xxx.png",
		title: "这是标题！！！"
}
```

运行到微信小程序、H5和app都是ok的。
hbuilder版本v2.42

附上截图（需科学上网）：
![image](https://user-images.githubusercontent.com/5440532/82851584-d04b5300-9f32-11ea-8db7-b86b5c4f02da.png)


如果对此有疑问，麻烦贴出可以重现的代码或demo，谢谢

**Comment by chenzefeng09** [comment]
[uni-test.zip](https://github.com/zhangdaren/miniprogram-to-uniapp/files/4679633/uni-test.zip)
我看了下我的情况，应该是这样，涉及到template的时候

@zhangdaren

**Comment by chenzefeng09** [comment]
应该是这行
https://github.com/zhangdaren/miniprogram-to-uniapp/blob/1616467e2dc353806b3f268c31735ac0bdf13ef8/src/wx2uni/project/templateTagHandle.js#L26
这个paramsHandle方法会将分号替换掉

@zhangdaren
