### ISSUE TITLE
app.json里面的tabBar的图片路径转化错误

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#35]
` "tabBar": {
    "color": "#AAAAAA",
    "selectedColor": "#34BE79",
    "borderStyle": "black",
    "backgroundColor": "#ffffff",
    "list": [
      {
        "pagePath": "pages/index/index",
        "text": "首页",
        "iconPath": "static/tabbar/home.png",
        "selectedIconPath": "static/tabbar/home-fill.png"
      },
      {
        "pagePath": "pages/explore/index",
        "text": "新闻",
        "iconPath": "static/tabbar/compass-discover-line.png",
        "selectedIconPath": "static/tabbar/compass-discover-fill.png"
      },
      {
        "pagePath": "pages/find/index",
        "text": "发现",
        "iconPath": "static/tabbar/find-line.png",
        "selectedIconPath": "static/tabbar/find-fill.png"
      },
      {
        "pagePath": "pages/personal/index",
        "text": "我的",
        "iconPath": "static/tabbar/user-line.png",
        "selectedIconPath": "static/tabbar/user-fill.png"
      }
    ]
  },

  转化后
  "tabBar": {
		"color": "#AAAAAA",
		"selectedColor": "#34BE79",
		"borderStyle": "black",
		"backgroundColor": "#ffffff",
		"list": [
			{
				"pagePath": "pages/recognize/index",
				"text": "首页",
				"iconPath": "./staticstatic/tabbar/home.png",
				"selectedIconPath": "./staticstatic/tabbar/home-fill.png"
			},
			{
				"pagePath": "pages/explore/index",
				"text": "新闻",
				"iconPath": "./staticstatic/tabbar/compass-discover-line.png",
				"selectedIconPath": "./staticstatic/tabbar/compass-discover-fill.png"
			},
			{
				"pagePath": "pages/find/index",
				"text": "发现",
				"iconPath": "./staticstatic/tabbar/find-line.png",
				"selectedIconPath": "./staticstatic/tabbar/find-fill.png"
			},
			{
				"pagePath": "pages/personal/index",
				"text": "我的",
				"iconPath": "./staticstatic/tabbar/user-line.png",
				"selectedIconPath": "./staticstatic/tabbar/user-fill.png"
			}
		]
	},`

**Comment by zhangdaren** [comment]
最新版v1.0.25应该无此问题了哈~
