### ISSUE TITLE
18号新版后var e = getApp();替换问题

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#39]
18号新版
var e = getApp(); 转换成了 var e = getApp().globalData; 

里面原来的e.globalData.resourceBasePath  还是e.globalData.resourceBasePath，应该换成e.resourceBasePath

**Comment by zhangdaren** [comment]
大佬你这源码是经过压缩的吗？

**Comment by zhangdaren** [comment]
目前来说尽可能的能解决一些问题，，比如搜集当前页面里面的getApp()的别名，然后在替换时，判断一下当前及父级父父级存不存在与这个别名一致的参数 ，然后再替换，尽可能不让误替换。

**Comment by zhangdaren** [comment]
v1.0.64应该是完美解决这个问题了，，使用的替换方式已经很先进，已经无视混淆变量了。
