### ISSUE TITLE
说一说我转换后的感受

### ISSUE THREAD

**Issue by godkun** [zhangdaren/miniprogram-to-uniapp#41]
目前感觉转换的不是很好，wx.api 转换后，还是wx.api，不能转成uni.api形式。这样转换后，感觉不是很爽，目前这个转换东西就是你自己平时在迭代么。uni官方有没有参与进来。

**Comment by zhangdaren** [comment]
wx的api，uni-app都可以支持，所以没必要转换，除非是有特定不支持的，所以现在工具并没有对这方面进行转换。

目前工具就我自己一人在维护。

**Comment by godkun** [comment]
一个人维护，不容易。感谢开源。我想的是，用 wx.api 转换成 uni.api ，然后再用 uni 的多端命令，转换成多端。如果是wx.api，应该就没法转多端了吧。不过想实现这种，感觉挺困难的

**Comment by zhangdaren** [comment]
> 一个人维护，不容易。感谢开源。我想的是，用 wx.api 转换成 uni.api ，然后再用 uni 的多端命令，转换成多端。如果是wx.api，应该就没法转多端了吧。不过想实现这种，感觉挺困难的

感谢支持，转换这个倒还好，有规则就可以的，能否提供一下，是哪些api呢？你的诉求就是说将wx替换为uni嘛？准备下个版本朝着这个方向努力，去wx。

**Comment by godkun** [comment]
你的微信是多少，我们可以交流一下，我可以和你一起做这个转换工具，就像taro的转换工具项目那样，做一个完善的东西

**Comment by zhangdaren** [comment]
你搜索一下我的qq吧，就是我的微信。
 

不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "杨昆"<notifications@github.com>; 
发送时间: 2019年10月29日(星期二) 凌晨0:12
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 说一说我转换后的感受 (#41)




你的微信是多少，我们可以交流一下，我可以和你一起做这个转换工具，就像taro的转换工具项目那样，做一个完善的东西
 
&mdash;

**Comment by zhangdaren** [comment]
> 一个人维护，不容易。感谢开源。我想的是，用 wx.api 转换成 uni.api ，然后再用 uni 的多端命令，转换成多端。如果是wx.api，应该就没法转多端了吧。不过想实现这种，感觉挺困难的

话说，大佬有测试，哪些命令在uni里别的平台不支持的吗？

刚刚翻看帖子：https://ask.dcloud.net.cn/article/35786

> wx.是否要替换为uni.？
关于js api中的wx.，不要全局替换为uni.。因为有的wx的api是微信独有的，替换为uni后，反而在微信下没法用了。

> 同时uni-app编译器提供了把wx.编译为不同平台的机制，所以直接使用wx.的api完全可以正常在各端运行。

> 所以对于老代码，替不替换不重要，不影响运行，只影响语法提示和转到定义。

> 但是新写的代码，还是要用uni.的api，在代码提示、转到定义方面更强大。

这个替换还是得从长计议了。
