### ISSUE TITLE
utils目录的app.js会被转化成app.vue

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#42]
1、utils目录的app.json会被转换成app.vue

 2、<view class="dot {{idx==currentSwiperSP?' active':''}}" wx:for="{{supports.length/10<1?supports.length/10+1:supports.length/10}}" wx:for-index="idx" wx:key="*"></view>
转化成
<view
							:class="'dot ' + (idx == currentSwiperSP ? ' active' : '')"
							v-for="(item, index) in supports.length / 10 < 1 ? supports.length / 10 + 1 : supports.length / 10"
							:key="index"
						></view>
此语句转化后语法错误
3、getApp().globalData后有globalData的重复调用出错

**Comment by zhangdaren** [comment]
> 1、utils目录的app.json会被转换成app.vue
> 
> 2、
> 转化成
> 
> 此语句转化后语法错误
> 3、getApp().globalData后有globalData的重复调用出错

收到，感谢大佬，下周修复。

**Comment by zhangdaren** [comment]
> 3、getApp().globalData后有globalData的重复调用出错

请问一下这个转换之前的代码是啥？

**Comment by zhangdaren** [comment]
> 2、
> 转化成
> 
> 此语句转化后语法错误


经过测试，代码转换后为：
`<view  v-for="(item, index) in supports.length/10<1?supports.length/10+1:supports.length/10" :key="index">test</view>`

配置数据：supports:[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]

**编译正常，微信小程序里正常，h5平台正常，app正常**

提个小疑问，如果supports.length不是10的倍数的话，h5平台运行，会报错：RangeError: Invalid array length

**Comment by zhangdaren** [comment]
> 1、utils目录的app.json会被转换成app.vue

经过测试，没有这种情况。是不是你的utils目录里有app.js文件？

**Comment by myfengstyle** [comment]
utils目录的app.js会被转化成app.vue

**Comment by zhangdaren** [comment]
> utils目录的app.js会被转化成app.vue

下版会优化这个判断逻辑。

**Comment by zhangdaren** [comment]
已修复。
