### ISSUE TITLE
setdata的建议也转换一下，还有wx.转换成uni.

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#43]
setdata的建议也转换一下，还有wx.转换成uni.

setdata的修改的地方还是比较多的，手动很费劲

**Comment by zhangdaren** [comment]
> setdata的建议也转换一下，还有wx.转换成uni.
> 
> setdata的修改的地方还是比较多的，手动很费劲

setData以前试过，但效果不怎么好，所以现在直接用一个函数来替代。
为啥还需要手动修改？
下个版本准备将wx都替换为uni。

**Comment by zhangdaren** [comment]
uni对wx的api做了兼容，所以暂时不会进行转换。也没必要。
