### ISSUE TITLE
解析TypeScript报错

### ISSUE THREAD

**Issue by MillerRen** [zhangdaren/miniprogram-to-uniapp#46]
在使用了TypeScript之后,class定义中使用了类似
```
class A {
  const a = 'a';
}
```
语法之后报错:
`[wx-to-uni-app]: Error: 解析文件出错: SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (3:10)`

**Comment by zhangdaren** [comment]
收到，晚点我测试一下，不出意思，这周六应该能更新一个版本。

**Comment by zhangdaren** [comment]
v1.0.42已经支持啦，

经过观察，发现目录下会同时存在一个ts和一个js的同名文件，因此直接解析js文件就好了

如有其他例外，麻烦告知哈，谢谢~~
