### ISSUE TITLE
App.vue文件都没有<script>标签，还有三元运算解析错误

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#49]
1、app.vue的js代码没有<script>标签
2、  `<view class="huiyy" hidden="{{group}}" wx:if="{{pay_type==1}}">{{group_sale.word}}（{{group_sale.room_discount<10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text>-{{sale_price}}元</text>
</view>`
转化成了：
`<view class="huiyy" :hidden="group" v-if="pay_type==1">{{group_sale.word}}（{{group_sale.room_discount<10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text>-{{sale_price}}元
    </10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text></view>
`

**Comment by myfengstyle** [comment]
类似的多处出现<text> has no matching end tag.错误

**Comment by myfengstyle** [comment]
<text> has no matching end tag.

**Comment by myfengstyle** [comment]
<text> has no matching end tag.

**Comment by myfengstyle** [comment]
<view class="huiyy" hidden="{{group}}" wx:if="{{pay_type==1}}">{{group_sale.word}}（{{group_sale.ticket_discount<10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）： <text> -{{sale_price}}元</text>
    </view>
    转化成了
    <view class="huiyy" :hidden="group" v-if="pay_type==1">{{group_sale.word}}（{{group_sale.ticket_discount<10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）： <text> -{{sale_price}}元
    </10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）：></view>

**Comment by myfengstyle** [comment]
`<view class="huiyy" hidden="{{group}}" wx:if="{{pay_type==1}}">{{group_sale.word}}（{{group_sale.ticket_discount<10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）： <text> -{{sale_price}}元</text>
    </view>
    转化成了
    <view class="huiyy" :hidden="group" v-if="pay_type==1">{{group_sale.word}}（{{group_sale.ticket_discount<10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）： <text> -{{sale_price}}元
    </10?group_sale.ticket_discount+'折（门票）':'无折扣'}}）：></view>`

**Comment by myfengstyle** [comment]
`<view class="huiyy" hidden="{{group}}" wx:if="{{pay_type==1}}">{{group_sale.word}}（{{group_sale.room_discount<10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text>-{{sale_price}}元</text>
</view>
转化成了：
<view class="huiyy" :hidden="group" v-if="pay_type==1">{{group_sale.word}}（{{group_sale.room_discount<10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text>-{{sale_price}}元
    </10?group_sale.room_discount+'折（客房）':'无折扣'}}）：<text></view>`

**Comment by myfengstyle** [comment]
` <view class="get-li">{{group.word}}（{{group.minishop_discount<10?group.minishop_discount+'折（微小店）':'无折扣'}}）：　<text style="color:#d70008;">-{{order_show.salePrice}}元</text>
        </view>
	转化成了：
	<view class="get-li">{{group.word}}（{{group.minishop_discount<10?group.minishop_discount+'折（微小店）':'无折扣'}}）：　<text style="color:#d70008;">-{{order_show.salePrice}}元
        </10?group.minishop_discount+'折（微小店）':'无折扣'}}）：　<text></view>`

**Comment by zhangdaren** [comment]
这些都是小程序的是代码是嘛？

**Comment by myfengstyle** [comment]
是的哦

**Comment by zhangdaren** [comment]
这个bug已修复，下个版本解决，顺便说一句：这样的语法，微信小程序开发工具没问题，而eslint过不了。。。

**Comment by zhangdaren** [comment]
app.vue的js代码没有<script>标签

**Comment by zhangdaren** [comment]
第一个问题已修复，v1.0.34
