### ISSUE TITLE
变量没有声明会导致转换时出错

### ISSUE THREAD

**Issue by Missna** [zhangdaren/miniprogram-to-uniapp#51]
在 src/wx2uni/wxmlHandle.js 中第85行，templateConvertedString 没有进行声明，会导致转换出现异常，看一下截图，两个不同文件，转换出来的内容是一样的，我将templateConvertedString用let 声明后，转换就正常了

![image](https://user-images.githubusercontent.com/22737005/70376915-2f97b580-1949-11ea-9a8d-0f9cda27285f.png)

![image](https://user-images.githubusercontent.com/22737005/70376940-4a6a2a00-1949-11ea-8ea1-04711c626636.png)

**Comment by zhangdaren** [comment]
是的哈，谢谢大佬，刚用另一种方式解决了，确实这里没有声明哇。

**Comment by zhangdaren** [comment]
v1.0.34已修复
