### ISSUE TITLE
新版的uniapp已经支持App.vue里面写的函数

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#52]
新版的uniapp已经支持App.vue里面写的函数

**Comment by zhangdaren** [comment]
是的，经过考虑，仍然还是采用globalData的方式来调用，原因如下：

在app.js里，globalData里可能已存在function和变量。
在page里，并没法区分getApp().xxx，后面的xxx究竟是函数还是变量，所以为了统一，一刀切，全整进globalData里，这样，在page里的调用方式也是统一的。
