### ISSUE TITLE
hidden属性转换出错

### ISSUE THREAD

**Issue by yyISACoder** [zhangdaren/miniprogram-to-uniapp#59]
原生项目中的hidden属性，在转换后变为了v-if,这样之前本该隐藏的元素就会都展示出来，逻辑就出问题了，望解决

**Comment by zhangdaren** [comment]
似乎有点明白了，应该是工具把它给整反了，，比如hidden="true"，转换后变成v-if="true"了，所以应该要再反一下，这个周一我看看，再更新一下。

**Comment by zhangdaren** [comment]
v1.0.47已解决这个问题，虽然手段有点粗暴哈~~

**Comment by zhangdaren** [comment]
v.1.0.59不再转换hidden，因为Uni-app本支持。
