### ISSUE TITLE
麻烦给js的代码加上<script></script>

### ISSUE THREAD

**Issue by Laney911** [zhangdaren/miniprogram-to-uniapp#65]
麻烦给页面和组件的js代码加上<script></script>

**Comment by zhangdaren** [comment]
可以发一下你的js代码吗？
你的要转换的微信小程序代码是不是uniapp编译生成的代码？

script标签确实未完全加入，下版加入

**Comment by Laney911** [comment]
有些script标签没加入，而且AST也没有实现作用。加一下QQ，发源码给你。

**Comment by Laney911** [comment]
QQ 772525925

**Comment by Laney911** [comment]
邮件发你

**Comment by Laney911** [comment]
这是小程序源码，你转换一下可以看到结果，缺少script标签，AST也没实现作用。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhangdaren"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 中午1:54
收件人:&nbsp;"zhangdaren/miniprogram-to-uniapp"<miniprogram-to-uniapp@noreply.github.com&gt;;
抄送:&nbsp;"蒙面黑侠"<772525925@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaren/miniprogram-to-uniapp] 麻烦给js的代码加上<script&gt;</script&gt; (#65)




可以发一下你的js代码吗？
 你的要转换的微信小程序代码是不是uniapp编译生成的代码？
 
script标签确实未完全加入，下版加入

**Comment by Laney911** [comment]
已经发你了

**Comment by zhangdaren** [comment]
大佬你代码发哪了？
&nbsp;

不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LaneyLau"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 下午2:08
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com&gt;; 
抄送: "张鹏"<375890534@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 麻烦给js的代码加上<script&gt;</script&gt; (#65)




已经发你了
 
&mdash;

**Comment by Laney911** [comment]
zhangdaren/miniprogram-to-uniapp <miniprogram-to-uniapp@noreply.github.com>


github.com邮箱

加我QQ发你也行 772525925

或者我加你QQ邮箱
