### ISSUE TITLE
建议以后能加ES5转ES6

### ISSUE THREAD

**Issue by Laney911** [zhangdaren/miniprogram-to-uniapp#66]
建议以后能加ES5转ES6

对，你没看错，就是ES5转ES6，也就是babel的逆向。
现在大部分浏览器或者工具框架 就已经大部分支持ES6语法或者会降级转为ES5

所以想冗余的ES5属于ES6语法的代码，可以转回去为ES6.

升级ES5语法为ES6语法。

**Comment by zhangdaren** [comment]
这个倒是可以研究一下，从简到繁容易 ，从繁到简繁琐。

**Comment by Laney911** [comment]
加我QQ772525925，时常给你一些语法转换构思， are you OK？

其实并不繁杂，ES6 语法也就那些，针对语法转换，无非做到两点，一个是检测这个ES5语法意思也就是检测，一个是转换，前者先标准再全面。没必要做全适配Babel的。

**Comment by zhangdaren** [comment]
> 加我QQ772525925，时常给你一些语法转换构思， are you OK？
> 
> 其实并不繁杂，ES6 语法也就那些，针对语法转换，无非做到两点，一个是检测这个ES5语法意思也就是检测，一个是转换，前者先标准再全面。没必要做全适配Babel的。

想了一下，工作量不小，比如：
```
for(var i = 1; i < 5; i++){
console.log(i);
}
console.log(i);
```
需要转换为：
```
for(var i = 1; i < 5; i++){
console.log(i);
}
console.log(i);
```
吧。

是的，什么也没转，但代码判断就比较复杂啦。。。

因为这个需求超出工具的边界了，如果你真想要实现这样一个功能，光想法还不够，我建议还是能够落地，有方案，有示例比较好。

我猜测，最多就能做上个箭头函数的转换，模板字符串的转换

什么扩展字符，let就非常麻烦了。
