### ISSUE TITLE
图片url被转换为相对路径

### ISSUE THREAD

**Issue by chenzefeng09** [zhangdaren/miniprogram-to-uniapp#67]
小程序代码
`<image wx:else class='item_img' src='http://img.yimutian.com/crm/5c18e4f26ef1433be581c7ffcb0aff48.png'></image>`
转换完后变成
`<image v-else class="item_img" src="/../../pages/price/http:/img.yimutian.com/crm/5c18e4f26ef1433be581c7ffcb0aff48.png"></image>`

给加了个相对路径的前缀，很奇怪

**Comment by zhangdaren** [comment]
感谢，这个是bug，今晚晚些时间将更新一版，即可解决。

**Comment by zhangdaren** [comment]
v1.0.59 已解决，请更新再试试。
