### ISSUE TITLE
wxParse移除不干净，部分函数内变量被替换成getAPP

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#68]
var t = function(t) {
    return t && t.__esModule ? t : {
        default: t
    };
}(require("../../wxParse/wxParse")), e = (getApp(), require("../../utils/request.js"));
这种(require("../../wxParse/wxParse"))没用清除

**Comment by zhangdaren** [comment]
有转换前的代码？
不过这种也正常吧，没有关键词判断了。工具对于混淆过、非源码不太友好。
