### ISSUE TITLE
wx.getStorage转化后缺少data

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#69]
`wx.getStorage({
				key: 'dengji',
				success: function(e) {
					t.dengji = e.data;
				}
			});`
被转化成了
`wx.getStorage({
				key: 'dengji',
				success: function(e) {
					t.dengji = e;
				}
			});`

缺少了data

**Comment by zhangdaren** [comment]
oh,god...
好吧，感谢，下版本解决一下。

**Comment by zhangdaren** [comment]
测试似乎没这问题，请更新为最新试试吧
