### ISSUE TITLE
大佬 们小程序六十多个页面转换过程没问题 之后uni跑不起来都是红

### ISSUE THREAD

**Issue by 54huige** [zhangdaren/miniprogram-to-uniapp#7]
大佬 们小程序六十多个页面转换过程没问题 之后uni跑不起来都是红

要不要发给你复现一下 改进咱们这个转换项目

**Comment by zhangdaren** [comment]
可以啊，现在确实还有一些问题。

**Comment by 54huige** [comment]
> 可以啊，现在确实还有一些问题。

大佬 我加你微信吧 或者我直接把源码文件发你邮箱  你这边捐赠码能放到git上吗？

**Comment by zhangdaren** [comment]
我的微信：wxid_4820628203312 
------------------
不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


 




------------------ 原始邮件 ------------------
发件人: "HuiHui"<notifications@github.com>; 
发送时间: 2019年7月19日(星期五) 下午3:32
收件人: "zhangdaren/miniprogram-to-uniap"<miniprogram-to-uniapp@noreply.github.com>; 
抄送: "张鹏"<375890534@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] 大佬 们小程序六十多个页面转换过程没问题 之后uni跑不起来都是红 (#7)



 
可以啊，现在确实还有一些问题。
  
大佬 我加你微信吧 或者我直接把源码文件发你邮箱  你这边捐赠码能放到git上吗？

**Comment by 54huige** [comment]
> 我的微信：wxid_4820628203312 ------------------ 不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！
> […](#)

这个微信号搜索不到 加我吧 heyunhui5201314
