### ISSUE TITLE
wxml的style没有分号，出现布局错误

### ISSUE THREAD

**Issue by myfengstyle** [zhangdaren/miniprogram-to-uniapp#71]
<view style="color:blackheight:37rpx;white-space:pre-wrap">
转化成
 <view style="color:blackheight:37rpxwhite-space:pre-wrap">
没有分号，这种情况很多

**Comment by zhangdaren** [comment]
有代码可以重现吗？

**Comment by zhangdaren** [comment]
问题关闭，如果还有问题，麻烦再发贴，感谢
