### ISSUE TITLE
小程序数据绑定再带data 转换App data变量找不到

### ISSUE THREAD

**Issue by ztj666** [zhangdaren/miniprogram-to-uniapp#72]
### 问题描述？
小程序数据绑定再带data 转换App data变量找不到
 <view v-for="(item, key) in data" :key="key">

**Comment by zhangdaren** [comment]
麻烦给出示例代码吧，，比如转换前的代码和转换后的代码

**Comment by ztj666** [comment]
转换前：
	<view wx:for="{{data}}" wx:key="key">
		<view class="job-items" bindtap="openmsg">
			<view class="job-item" data-jid='{{item.id}}' bindtap="goToJob" data-id="{{item.id}}">
				<view class="job-duty">{{item.jobName}}</view>
				<view class="job-inc">{{item.entName}}</view>
				<view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
			</view>
		</view>
	</view>
转换后：
  <view v-for="(item, key) in data" :key="key">
<view class="job-items" @tap="openmsg">
  	<view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id">
  		 <view class="job-duty">{{item.jobName}}</view>
 			 <view class="job-inc">{{item.entName}}</view>
   		 <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
 		 </view> 
	</view>
</view>

**Comment by ztj666** [comment]
转换前
`  <view v-for="(item, key) in data" :key="key">
<view class="job-items" @tap="openmsg">
  	<view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id">
  		 <view class="job-duty">{{item.jobName}}</view>
 			 <view class="job-inc">{{item.entName}}</view>
   		 <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
 		 </view> 
	</view>
</view> `

转换后
`  <view v-for="(item, key) in data" :key="key">
<view class="job-items" @tap="openmsg">
  	<view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id">
  		 <view class="job-duty">{{item.jobName}}</view>
 			 <view class="job-inc">{{item.entName}}</view>
   		 <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
 		 </view> 
	</view>
</view> `

**Comment by zhangdaren** [comment]
转换前后一样啊------------------ 原始邮件 ------------------
发件人: "ztj666"<notifications@github.com>
发送时间: 2020年4月13日(星期一) 中午11:27
收件人: "zhangdaren/miniprogram-to-uniapp"<miniprogram-to-uniapp@noreply.github.com>;
抄送: "zhangdaren"<375890534@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [zhangdaren/miniprogram-to-uniapp] 小程序数据绑定再带data 转换App data变量找不到 (#72)




 
转换前
  <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view>  </view> </view>
 
转换后
  <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view>  </view> </view>
 
&mdash;

**Comment by ztj666** [comment]
> 转换前后一样啊------------------ 原始邮件 ------------------ 发件人: "ztj666"<notifications@github.com> 发送时间: 2020年4月13日(星期一) 中午11:27 收件人: "zhangdaren/miniprogram-to-uniapp"<miniprogram-to-uniapp@noreply.github.com>; 抄送: "zhangdaren"<375890534@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [zhangdaren/miniprogram-to-uniapp] 小程序数据绑定再带data 转换App data变量找不到 (#72) 转换前 <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view> </view> </view> 转换后 <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view> </view> </view> &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
不好意思拷错了 转换前
	<view wx:for="{{data}}" wx:key="key">
		<view class="job-items" bindtap="openmsg">
			<view class="job-item" data-jid='{{item.id}}' bindtap="goToJob" data-id="{{item.id}}">
				<view class="job-duty">{{item.jobName}}</view>
				<view class="job-inc">{{item.entName}}</view>
				<view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
			</view>
		</view>
	</view>

**Comment by ztj666** [comment]
> 转换前后一样啊------------------ 原始邮件 ------------------ 发件人: "ztj666"<notifications@github.com> 发送时间: 2020年4月13日(星期一) 中午11:27 收件人: "zhangdaren/miniprogram-to-uniapp"<miniprogram-to-uniapp@noreply.github.com>; 抄送: "zhangdaren"<375890534@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [zhangdaren/miniprogram-to-uniapp] 小程序数据绑定再带data 转换App data变量找不到 (#72) 转换前 <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view> </view> </view> 转换后 <view v-for="(item, key) in data" :key="key"> <view class="job-items" @tap="openmsg"> <view class="job-item" data-jid="21" @tap="goToJob" :data-id="item.id"> <view class="job-duty">{{item.jobName}}</view> <view class="job-inc">{{item.entName}}</view> <view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view> </view> </view> </view> &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

不好意思考错了 转换前`	<view wx:for="{{data}}" wx:key="key">
		<view class="job-items" bindtap="openmsg">
			<view class="job-item" data-jid='{{item.id}}' bindtap="goToJob" data-id="{{item.id}}">
				<view class="job-duty">{{item.jobName}}</view>
				<view class="job-inc">{{item.entName}}</view>
				<view class="job-salary">{{item.salaryMin}}~{{item.salaryMax}}元</view>
			</view>
		</view>
	</view>`

**Comment by zhangdaren** [comment]
看起来没毛病啊，，应该转换为哪样？

**Comment by zhangdaren** [comment]
wxml和Js都可以发一下吗？

**Comment by ztj666** [comment]
> wxml和Js都可以发一下吗？

发你邮箱了
转换后 data没有数据 重新定义一个就可以了
