### ISSUE TITLE
转换后van-picker 无法加载数据

### ISSUE THREAD

**Issue by ztj666** [zhangdaren/miniprogram-to-uniapp#73]
### 问题描述？
<van-popup :show="areaOfWorkShow" position="bottom">
	<van-picker show-toolbar :columns="areaOfWork" title="选择工作区域" @cancel="closeArea" @confirm="saveArea"></van-picker>
</van-popup>

### 期望的结果

数据无法加载到van-paicker插件 感觉是插件转换后不兼容
vanpaicker不渲染数据

**Comment by ztj666** [comment]
``<template>
<view>
	<view class="weui-cell weui-cell_access" hover-class="weui-cell_active" @tap="openTypeOfWenhua">
							<view class="weui-cell__bd">文化程度</view>
							<view class="weui-cell__ft weui-cell__ft_in-access">{{typeofwenhua}}</view>
						</view>


<van-popup :show="wenhuaShow" position="bottom" >
	<van-picker show-toolbar :columns="wenhua" value-key="text" title="文化程度" @cancel="closeWenhua" @confirm="saveWenhua"></van-picker>
</van-popup>

</view>
</template>


<script>

global['__wxRoute'] = 'pages/idregister/index';

const WXAPI = require('../../weixinapi/weixinapi');
const app = getApp()
var opt1 = [];
var opt2 = [];
var list_url = '';
Page({
  data: {
    wenhuaShow: false,
    wenhuaOfId: '',
	wenhua:[],
    wenhuaString: ""
  },
  saveWenhua(event) {
	  console.log('saveWenhua')
	  console.log(event);
    const {
      picker,
      value,
      index
    } = event.detail;
    this.setData({
      wenhuaOfId: value.id,
      typeofwenhua: value.text,
      wenhuaShow: false
    })
  },
  openTypeOfWenhua() {
  //文化程度
    this.setData({
      wenhuaShow: true
    });
  },
  closeWenhua() {
  //文化程度
    this.setData({
      wenhuaShow: false
    });
  },
 
  onLoad: function (options) {
	   console.log("idregister");
    var that = this;
    
    WXAPI.getWhcd({}).then(function (res) {
		console.log('文化程度：')
		console.log(res)
      if (res.code == 200) {
        var opt1 = [];
        for (var i = 0; i < res.data.length; i++) {
          opt1.push({
            text: res.data[i]["name"],
            id: res.data[i]["code"]
          });
        }
        that.setData({
          wenhua: opt1
        });
		console.log(that.wenhua)
      }
    });
   
  },
})
export default global['__wxComponents']['pages/idregister/index'];
</script>
<style>
@import "./index.css";
</style>

**Comment by zhangdaren** [comment]
感觉是组件的加载方式没转换对，，请尝试v1.0.64吧，组件加载方式已优化。
