### ISSUE TITLE
转换报错，只有css生成

### ISSUE THREAD

**Issue by chenzefeng09** [zhangdaren/miniprogram-to-uniapp#78]
### 问题描述？
转换我的项目时，报错如下

`
文件类型: Page       路径: ../miniapp-douniu/prepay/pages/apply_advance_pay/apply_advance_pay.js
(node:17820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at dataArr.forEach.obj (/usr/local/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:191:44)
    at Array.forEach (<anonymous>)
    at defineValueHandle (/usr/local/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:190:13)
    at componentTemplateBuilder (/usr/local/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:392:5)
    at jsHandle (/usr/local/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js:1102:35)
    at /usr/local/lib/node_modules/miniprogram-to-uniapp/src/index.js:658:54
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:17820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
生成的项目里只有css文件生成了，wxml和js都没有
![image](https://user-images.githubusercontent.com/7556537/82555495-7812fa80-9b9a-11ea-9c2e-b07f5d7f30cc.png)

**Comment by zhangdaren** [comment]
wtu -V的版本是多少？
看起来是你/miniapp-douniu/prepay/pages/apply_advance_pay/apply_advance_pay.js这个页面，或者别的页面里面的data属性里面有非常规写法，可以贴一下嘛？

**Comment by chenzefeng09** [comment]
![image](https://user-images.githubusercontent.com/7556537/82623052-daf3a880-9c11-11ea-9732-c508f7db7d6c.png)

**Comment by chenzefeng09** [comment]
![image](https://user-images.githubusercontent.com/7556537/82623192-273ee880-9c12-11ea-83c1-77a4322ffe3f.png)

**Comment by zhangdaren** [comment]
![image](https://user-images.githubusercontent.com/5440532/82623593-1d69b500-9c13-11ea-83d3-84e9acf91dd5.png)

似乎我已经定位到原因了，，麻烦，找到：/usr/local/lib/node_modules/miniprogram-to-uniapp/src/wx2uni/jsHandle.js 这个文件，将上面里line: 186~196行删除，然后再试试呢？

**Comment by chenzefeng09** [comment]
会报这个找不到
![image](https://user-images.githubusercontent.com/7556537/82624003-273fe800-9c14-11ea-861d-391976db059d.png)

**Comment by chenzefeng09** [comment]
![image](https://user-images.githubusercontent.com/7556537/82628246-ed281380-9c1e-11ea-839b-90b2316d97f1.png)
改成这样，可以转换出vue了

**Comment by chenzefeng09** [comment]
#79
