### ISSUE TITLE
自定义的Component编译之后各种问题 怎么办

### ISSUE THREAD

**Issue by 54huige** [zhangdaren/miniprogram-to-uniapp#8]
小程序的Component自定义组件编译之后无法使用

**Comment by zhangdaren** [comment]
请使用新版试试，明天将更新。

**Comment by 54huige** [comment]
> 请使用新版试试，明天将更新。

好的 期待大佬成果 一定支持大佬

**Comment by zhangdaren** [comment]
感谢支持，已经更新了哈~~，对于一部分自定义组件如wxparse目前还没有特别好的方法，但自己定义的组件应该没问题了
