### ISSUE TITLE
还要配 wtu 的环境变量么?我 install 成功之后输入 wtu -V 提示  'wtu' 不是内部或外部命令，也不是可运行的程序 或批处理文件

### ISSUE THREAD

**Issue by gh852195168** [zhangdaren/miniprogram-to-uniapp#81]

**Comment by ccvv116** [comment]
我也是

**Comment by zhangdaren** [comment]
理论上不需要配，重装node试试，node安装到默认目录，如果不行就配置wtu的目录到系统环境变量吧。

**Comment by ccvv116** [comment]
windows下 node10 
'npm install miniprogram-to-uniapp - g' 换成 'npm install - g miniprogram-to-uniapp' 就好了╮(╯-╰)╭

**Comment by zhangdaren** [comment]
可能是之前文档出问题，-g中间有空格导致的吧？

**Comment by renaiqin** [comment]
同样的问题，请问怎么解决

**Comment by zhangdaren** [comment]
> 同样的问题，请问怎么解决

试试重装node，并且node安装在默认目录！！！ 发现报这个错的基本都是装在其他盘的。

如果还不行，请尝试把wtu的目录添加到系统的环境变量

如果还不行，建议使用hbuilder X 同名插件，不依赖环境，插件地址：https://ext.dcloud.net.cn/plugin?id=2656
