### ISSUE TITLE
微信小程序转uni-app,组件方法selectComponent这种方式不能获取，请问有什么方法获取组件方法

### ISSUE THREAD

**Issue by wyying** [zhangdaren/miniprogram-to-uniapp#83]
### 问题描述？
微信小程序转uni-app,组件方法selectComponent这种方式不能获取
请问有什么方法获取组件方法

### 重现步骤
1.转换完成，启动项目
一直提示
[Vue warn]: Property or method "hide" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

尝试了this.$scope.selectComponent，还是一样报错，也尝试了this.$refs.myTab.selectTab(0)方法，也是一样结果

### 期望的结果

能直接获取组件方法

**Comment by zhangdaren** [comment]
[图片]

小程序 里面的this.selectComponent ，在uniapp里面测试换为$refs是可以成功调用到组件里面的方法的，，记住，不能在onload里直接调，需要包一层 $nextTick，其他生命周期不需要。

**Comment by zzy-life** [comment]
> [图片]
> 
> 小程序 里面的this.selectComponent ，在uniapp里面测试换为$refs是可以成功调用到组件里面的方法的，，记住，不能在onload里直接调，需要包一层 $nextTick，其他生命周期不需要。

wxs里怎么调用呢？获取不到实例
![image](https://github.com/user-attachments/assets/e8b22f72-dd0d-4130-b356-209a80e14ea5)
![image](https://github.com/user-attachments/assets/5e3531fa-f983-42c2-ae27-dd810d3f8fc2)

**Comment by zzy-life** [comment]
搞定了....
正确的：
![image](https://github.com/user-attachments/assets/4857000f-6a9f-4515-9fdc-7a5063331413)
