### ISSUE TITLE
import导入时，将点号后的给忽略掉了

### ISSUE THREAD

**Issue by dvien** [zhangdaren/miniprogram-to-uniapp#86]
### 问题描述？

import {SymbolIterator} from "./methods/symbol.iterator";
导入后变成了
import {SymbolIterator} from "./methods/symbol";

### 重现步骤

https://github.com/ecjia/npm-ecjia-collect
第84行
用工具转换后直接变成了import {SymbolIterator} from "./methods/symbol";

### 期望的结果

import {SymbolIterator} from "./methods/symbol.iterator";

**Comment by zhangdaren** [comment]
感谢，下版解决。
