### ISSUE TITLE
转换后，自定义组件报错，无法运行小程序

### ISSUE THREAD

**Issue by Lemon71** [zhangdaren/miniprogram-to-uniapp#87]
一开始是自己写的组件和vant的组件路径有问题无法编译成小程序，改完之后在小程序的控制台报这个错误，无法运行

TypeError: Cannot read property 'components/base-rade/index' of undefined

![image](https://user-images.githubusercontent.com/32609874/99651583-c34a8f00-2a91-11eb-9d70-3a2b70828daa.png)

我看了下他是说这里的 global['__wxComponents']
![image](https://user-images.githubusercontent.com/32609874/99651891-20dedb80-2a92-11eb-8431-fbf5dfe4c9ea.png)

请问如何解决？

**Comment by zhangdaren** [comment]
应该在转换完后，在控制台信息最后，有输出一句：   
**因uniapp限制，当前转换后的Uniapp项目仅支持app和H5** ！！！仅支持app和H5 ！！！仅支持app和H5 ！！！**   

是的，，vant项目转换后，仅支持app和h5，所以不支持小程序，所以就报错了，   
因为某些原因，uniapp对小程序的一些语法没法很好的支持，导致vant的转换挺那个繁琐+复杂的，后面也许会支持。。   

现在的建议是vant的项目，建议换ui吧   
现在vant转换的项目，js代码还是小程序代码，template里面是vue的语法，所以二次开发起来有点反人类，不太推荐使用。

**Comment by Lemon71** [comment]
感谢大佬解惑，是我有点混淆看错了以为是weapp
