### ISSUE TITLE
关于小程序TS转换

### ISSUE THREAD

**Issue by ZJH9Rondo** [zhangdaren/miniprogram-to-uniapp#88]
### 问题描述？
 看了相关文档和issue，项目只说支持TS转换，在TypeScript这块并未有相关的Demo，实际表现是：TS相关的代码在转换中并未做任何改动，不符合预期

**Comment by zhangdaren** [comment]
目前不支持纯TS项目，需要使用小程序开发工具TS转换为JS，然后再进行转换。
