### ISSUE TITLE
可以转换H5吗

### ISSUE THREAD

**Issue by marcelowu** [zhangdaren/miniprogram-to-uniapp#89]
请问这个可以转换uniapp H5吗

https://github.com/qwqoffice/woocommerce-to-wechatapp-mini/tree/master/wechatapp

**Comment by marcelowu** [comment]
![捕获](https://user-images.githubusercontent.com/30912144/100920262-9d71b100-34b9-11eb-9def-31ed5f150288.PNG)

**Comment by zhangdaren** [comment]
理论上可以，，不过看了一下，他是这种结构：Page(Object.assign({}, app.Methods, {})

**Comment by marcelowu** [comment]
我替换Page(Object.assign({}, app.Methods, {}) 成 Page({}) 但是以下两个文件还是出差，帮忙看看是否还有别的需要改，
https://github.com/qwqoffice/woocommerce-to-wechatapp-mini/blob/master/wechatapp/pages/order-list/order-list.js
https://github.com/qwqoffice/woocommerce-to-wechatapp-mini/blob/master/wechatapp/pages/product-detail/product-detail.js

![捕获](https://user-images.githubusercontent.com/30912144/101050775-7bcd0400-3563-11eb-9fe8-39672a13a2ce.PNG)
