### ISSUE TITLE
[bug]  setData 方法有问题.. 求解决.. 

### ISSUE THREAD

**Issue by james-rh** [zhangdaren/miniprogram-to-uniapp#9]
` 
 changeMode: function () {
    "block" == this.data.listmode ? this.setData({
      listmode: ""
    }) : this.setData({
      listmode: "block"
    })
  },

`

遇到这种情况的 setData写法,  就会报错..   这是个bug啊..  

只认识带分号的语法 this.setData({
      listmode: ""
    });  , 而不认识类似运算符不带分号的语法  this.setData({
      listmode: ""
    })

**Comment by zhangdaren** [comment]
大佬的写法非常老练啊，下版增加setData()方法，来避免这个问题。
还有些bug未处理，将于下周一二一并更新。

**Comment by zhangdaren** [comment]
已解决，请更新再试。
