### ISSUE TITLE
props 转换相关问题反馈

### ISSUE THREAD

**Issue by cuiko** [zhangdaren/miniprogram-to-uniapp#91]
转换的时候默认值可以自动加上吗?

![QQ截图20210104150208](https://user-images.githubusercontent.com/33982919/103509658-97973300-4e9e-11eb-8340-92a3aa7f271d.png)
![QQ截图20210104150347](https://user-images.githubusercontent.com/33982919/103509678-a2ea5e80-4e9e-11eb-96cb-9f3749228501.png)

自定义组件相关源码
![image](https://user-images.githubusercontent.com/33982919/103509906-18eec580-4e9f-11eb-8311-999fd9035e2e.png)

**Comment by cuiko** [comment]
自定义组件相关源码
![image](https://user-images.githubusercontent.com/33982919/103509906-18eec580-4e9f-11eb-8311-999fd9035e2e.png)

**Comment by cuiko** [comment]
![image](https://user-images.githubusercontent.com/33982919/103512311-7422b700-4ea3-11eb-8985-8632c16ef6e5.png)
![image](https://user-images.githubusercontent.com/33982919/103512346-7e44b580-4ea3-11eb-911b-3bc31c587018.png)

**Comment by cuiko** [comment]
props object/array 类型的转换应该还能优化一下吧
![image](https://user-images.githubusercontent.com/33982919/103512578-edbaa500-4ea3-11eb-9f5c-2cdb3c29cea1.png)
![image](https://user-images.githubusercontent.com/33982919/103512540-d8de1180-4ea3-11eb-9630-e1acdc27ec07.png)

**Comment by cuiko** [comment]
如果是我哪里操作有问题也请各位大佬指点一下, 我也是个新手...

**Comment by zhangdaren** [comment]
不好意思，可以上代码嘛？ git的图被墙了，看不到了，或者请加我的q：375980534

**Comment by zhangdaren** [comment]
> props object/array 类型的转换应该还能优化一下吧
> ![image](https://user-images.githubusercontent.com/33982919/103512578-edbaa500-4ea3-11eb-9f5c-2cdb3c29cea1.png)
> ![image](https://user-images.githubusercontent.com/33982919/103512540-d8de1180-4ea3-11eb-9630-e1acdc27ec07.png)

理论上有对，array和object进行了处理的。估计是没识别到，，麻烦提供相关js文件，，

我代码里面有对如下场景有作处理：
///////////////////////////////
                    // proE: {
                    // 	type: Array,
                    // 	value: []
                    // }
                    //-->
                    // proE: {
                    // 	type: Array,
                    // 	default: () => []
                    // }
                    ///////////////////////////////
                    // proE: {
                    // 	type: Object,
                    // 	value: {}
                    // }
                    //-->
                    // proE: {
                    // 	type: Object,
                    // 	default: () => ({})
                    // }

**Comment by cuiko** [comment]
> > props object/array 类型的转换应该还能优化一下吧
> > ![image](https://user-images.githubusercontent.com/33982919/103512578-edbaa500-4ea3-11eb-9f5c-2cdb3c29cea1.png)
> > ![image](https://user-images.githubusercontent.com/33982919/103512540-d8de1180-4ea3-11eb-9630-e1acdc27ec07.png)
> 
> 理论上有对，array和object进行了处理的。估计是没识别到，，麻烦提供相关js文件，，
> 
> 我代码里面有对如下场景有作处理：
> ///////////////////////////////
> // proE: {
> // type: Array,
> // value: []
> // }
> //-->
> // proE: {
> // type: Array,
> // default: () => []
> // }
> ///////////////////////////////
> // proE: {
> // type: Object,
> // value: {}
> // }
> //-->
> // proE: {
> // type: Object,
> // default: () => ({})
> // }

源码:
```js
// ...
Component({
  properties: {
    // ...
    options: {
      value: [],
      type: Array
    },
    // ...
  }
})
// ...
```
转换后:
```js
// ...
export default {
  // ...
  props: {
    // ...
    options: {
      default: [],
      type: Array
    }
    // ...
  }
  // ...
}
// ...
```

**Comment by cuiko** [comment]
已向您的 QQ 发了好友申请

**Comment by zhangdaren** [comment]
> 已向您的 QQ 发了好友申请

好的，，

**Comment by cuiko** [comment]
项目源码部分 (src) 的组件用的是 ts 写的, 然后 examples 文件内是 js, 不过好像命令只对 src 文件夹进行了转换, 所以我进行了两次转换, 一次是对整个小程序源码 (ts) 进行了转换, 以及对 examples 文件夹单独进行转换, 两次的转换结果好像都一样, 都是:
```vue
export default {
  props: {
    options: {
      defalult: [],
      type: Array
    }
  }
}
```

wtu: v1.0.76
参数: -i -c -w- m

如果哪里表达的不太好, 麻烦大佬们指正, 互相进步嘛.

**Comment by zhangdaren** [comment]
> 项目源码部分 (src) 的组件用的是 ts 写的, 然后 examples 文件内是 js, 不过好像命令只对 src 文件夹进行了转换, 所以我进行了两次转换, 一次是对整个小程序源码 (ts) 进行了转换, 以及对 examples 文件夹单独进行转换, 两次的转换结果好像都一样, 都是:
> 
> ```js
> export default {
>   props: {
>     options: {
>       defalult: [],
>       type: Array
>     }
>   }
> }
> ```
> 
> wtu: v1.0.76
> 参数: -i -c -w- m
> 
> 如果哪里表达的不太好, 麻烦大佬们指正, 互相进步嘛.

目前对于ts的转换还是依赖于先需手工转换ts为js才能进行转换。。

可以提供一下，转换前的有问题的js代码？我测试一下，另外没收到好友申请。。。

**Comment by cuiko** [comment]
> > 项目源码部分 (src) 的组件用的是 ts 写的, 然后 examples 文件内是 js, 不过好像命令只对 src 文件夹进行了转换, 所以我进行了两次转换, 一次是对整个小程序源码 (ts) 进行了转换, 以及对 examples 文件夹单独进行转换, 两次的转换结果好像都一样, 都是:
> > ```js
> > export default {
> >   props: {
> >     options: {
> >       defalult: [],
> >       type: Array
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > wtu: v1.0.76
> > 参数: -i -c -w- m
> > 如果哪里表达的不太好, 麻烦大佬们指正, 互相进步嘛.
> 
> 目前对于ts的转换还是依赖于先需手工转换ts为js才能进行转换。。
> 
> 可以提供一下，转换前的有问题的js代码？我测试一下，另外没收到好友申请。。。

我也有对转换后的文件夹 (js) 进行了转换, 也是一样的问题...

部分源码 (其他公司的代码... 不方便贴太全, 望理解)
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// ...
const WEEKANEME = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
Component({
    ready() {
        this.initDate();
    },
    properties: {
        value: {
            value: '',
            type: String,
            observer(newVal) {
                this.setData({
                    _value: newVal
                }, () => {
                    this.backToActive();
                });
            }
        },
        start: {
            value: dayjs().subtract(3, 'month').format('YYYY-MM-DD'),
            type: String,
            observer() {
                this.initDate();
            }
        },
        end: {
            value: dayjs().add(1, 'year').format('YYYY-MM-DD'),
            type: String,
            observer() {
                this.initDate();
            }
        },
        mode: {
            value: 'multiple',
            type: String,
            observer(_mode) {
                this.setData({
                    _mode,
                });
            }
        },
        options: {
            value: [],
            type: Array,
        },
        includes: {
            value: [],
            type: Array
        },
        excludes: {
            value: [],
            type: Array
        },
        section: {
            value: false,
            type: Boolean,
        },
        sectionStart: {
            value: '',
            type: String,
        },
        sectionEnd: {
            value: '',
            type: String,
        },
        period: {
            value: false,
            type: Boolean
        },
        periodList: {
            value: [],
            type: Array
        },
        beginIndex: {
            value: -1,
            type: Number
        },
        endIndex: {
            value: -1,
            type: Number
        }
    },
    data: {
        _weekName: WEEKANEME,
        _value: dayjs().format('YYYY-MM-DD'),
        _current: 1,
        _mode: 'multiple',
        _month: [],
        _week: [],
        _sectionDate: '',
        _sectionSwitch: 0b00,
        _sectionIndex: [],
        showSection: true
    },
    methods: {
      // ...
    },
});
```

好友申请了呀,  375980534

**Comment by zhangdaren** [comment]
> > > 项目源码部分 (src) 的组件用的是 ts 写的, 然后 examples 文件内是 js, 不过好像命令只对 src 文件夹进行了转换, 所以我进行了两次转换, 一次是对整个小程序源码 (ts) 进行了转换, 以及对 examples 文件夹单独进行转换, 两次的转换结果好像都一样, 都是:
> > > ```js
> > > export default {
> > >   props: {
> > >     options: {
> > >       defalult: [],
> > >       type: Array
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > > wtu: v1.0.76
> > > 参数: -i -c -w- m
> > > 如果哪里表达的不太好, 麻烦大佬们指正, 互相进步嘛.
> > 
> > 
> > 目前对于ts的转换还是依赖于先需手工转换ts为js才能进行转换。。
> > 可以提供一下，转换前的有问题的js代码？我测试一下，另外没收到好友申请。。。
> 
> 我也有对转换后的文件夹 (js) 进行了转换, 也是一样的问题...
> 
> 部分源码 (其他公司的代码... 不方便贴太全, 望理解)
> 
> ```js
> "use strict";
> Object.defineProperty(exports, "__esModule", { value: true });
> // ...
> const WEEKANEME = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
> Component({
>     ready() {
>         this.initDate();
>     },
>     properties: {
>         value: {
>             value: '',
>             type: String,
>             observer(newVal) {
>                 this.setData({
>                     _value: newVal
>                 }, () => {
>                     this.backToActive();
>                 });
>             }
>         },
>         start: {
>             value: dayjs().subtract(3, 'month').format('YYYY-MM-DD'),
>             type: String,
>             observer() {
>                 this.initDate();
>             }
>         },
>         end: {
>             value: dayjs().add(1, 'year').format('YYYY-MM-DD'),
>             type: String,
>             observer() {
>                 this.initDate();
>             }
>         },
>         mode: {
>             value: 'multiple',
>             type: String,
>             observer(_mode) {
>                 this.setData({
>                     _mode,
>                 });
>             }
>         },
>         options: {
>             value: [],
>             type: Array,
>         },
>         includes: {
>             value: [],
>             type: Array
>         },
>         excludes: {
>             value: [],
>             type: Array
>         },
>         section: {
>             value: false,
>             type: Boolean,
>         },
>         sectionStart: {
>             value: '',
>             type: String,
>         },
>         sectionEnd: {
>             value: '',
>             type: String,
>         },
>         period: {
>             value: false,
>             type: Boolean
>         },
>         periodList: {
>             value: [],
>             type: Array
>         },
>         beginIndex: {
>             value: -1,
>             type: Number
>         },
>         endIndex: {
>             value: -1,
>             type: Number
>         }
>     },
>     data: {
>         _weekName: WEEKANEME,
>         _value: dayjs().format('YYYY-MM-DD'),
>         _current: 1,
>         _mode: 'multiple',
>         _month: [],
>         _week: [],
>         _sectionDate: '',
>         _sectionSwitch: 0b00,
>         _sectionIndex: [],
>         showSection: true
>     },
>     methods: {
>       // ...
>     },
> });
> ```
> 
> 好友申请了呀, 375980534

是我写错了，，，，是375890534

**Comment by zhangdaren** [comment]
你这份代码，我等下看看吧，没事，只要可以复现的关键代码就行了
