### ISSUE TITLE
微信小程序转uniapp 运行到手机模拟器上报错

### ISSUE THREAD

**Issue by windmill1992** [zhangdaren/miniprogram-to-uniapp#92]
### 问题描述？
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: (0 , _component.VantComponent) is not a function

TypeError: (0 , _component.VantComponent) is not a function
15:03:16.946 [JS Framework] Failed to execute the callback function:
15:03:16.966 TypeError: Cannot read property '__call_hook' of undefined
15:03:16.986 reportJSException >>>> exception function:__WEEX_CALL_JAVASCRIPT__, exception:JavaScript execute error!Uncaught TypeError: Cannot read property '__call_hook' of undefined

**Comment by zhangdaren** [comment]
项目是vant项目吗？？如果是，请使用命令行转换，并且在正常的命令行后面，添加“-z”参数 ，以便转换vant项目，，目前，vant项目仅支持h5和app
