### ISSUE TITLE
vue-cli模式转换失败

### ISSUE THREAD

**Issue by devilwjp** [zhangdaren/miniprogram-to-uniapp#96]
### 问题描述？
【vue-cli模式转换失败】版本1.0.76，系统win 10
原因是全局安装完之后，npm包的src/wx2uni/vue-cli目录中没有.gitignore文件，转换命令找不到此文件就会报错
PS：github仓库里是有的，1.0.76的npm包里没有

详细报错日志：
E:\works\native_to_uni>wtu -i "./" -c true
sourceFolder E:\works\native_to_uni
outputFolder = E:\works\native_to_uni_uni
targetFolder = E:\works\native_to_uni_uni\src
Convert app.css success!
Convert pages\logs\logs.css success!
Convert pages\index\index.css success!
Convert App.vue success!
Convert component utils\util.js success!
Convert pages\logs\logs.vue success!
Convert pages\index\index.vue success!
write pages.json success!
write manifest.json success!
write main.js success!
copy public/index.html success!
Error: ENOENT: no such file or directory, stat 'C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\src\wx2uni\vue-cli\.gitignore'
    at Object.statSync (fs.js:859:3)
    at Object.statSync (C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\node_modules\graceful-fs\polyfills.js:311:34)
    at getStatsSync (C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\node_modules\fs-extra\lib\util\stat.js:90:33)
    at Object.copySync (C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\src\wx2uni\vueCliHandle.js:105:28
    at new Promise (<anonymous>)
    at vueCliHandle (C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\src\wx2uni\vueCliHandle.js:34:15)
    at C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\src\index.js:1292:17 {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\devil\\AppData\\Roaming\\nvm\\v12.2.0\\node_modules\\miniprogram-to-uniapp\\src\\wx2uni\\vue-cli\\.gitignore'
}

### 重现步骤
wtu -i "xxxxxx" -c

### 期望的结果
希望能转换成功

**Comment by zhangdaren** [comment]
你可以先把这个文件复制到 'C:\Users\devil\AppData\Roaming\nvm\v12.2.0\node_modules\miniprogram-to-uniapp\src\wx2uni\vue-cli.gitignore'吧

准备发v1.1版本（-c这个模式弱化了，即不推荐，但功能还在，因为感觉属实麻烦）

现在vue cli这种用得多吗？

**Comment by devilwjp** [comment]
天生不喜欢hb，我相信大部分的高阶用户都还是习惯vscode和webstorm

**Comment by zhangdaren** [comment]
可以，待发布1.0版本，将会处理这个和vant。
话说，用vue-cli模式，是不是需要安装node-sass，感觉这个挺麻烦了，每次都要安装，不知道是不是我的操作方式不对？
&nbsp;

不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 凌晨2:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] vue-cli模式转换失败 (#96)





 
天生不喜欢hb，我相信大部分的高阶用户都还是习惯vscode和webstorm

**Comment by devilwjp** [comment]
安装一次即可，并不需要每次安装，理论上就npm或者yarn一次即可

**Comment by zhangdaren** [comment]
嗯，对于某一个项目是可以这样说哈，后续我再优化一下吧。&nbsp;

不管你是逐渐繁华，还是即将枯萎，此时此刻才是你的人生！


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhangdaren/miniprogram-to-uniapp] vue-cli模式转换失败 (#96)





 
安装一次即可，并不需要每次安装，理论上就npm或者yarn一次即可
 
&mdash;

**Comment by zhangdaren** [comment]
v1.1.3已经更新了cli模式的文件，可以再尝试一下

**Comment by devilwjp** [comment]
👌
