### ISSUE TITLE
windows版本的hbx3.1.9转换的小程序项目后不是标准的uni-app项目

### ISSUE THREAD

**Issue by lbnt1982** [zhangdaren/miniprogram-to-uniapp#97]
### 问题描述？
windows版本的hbx3.1.9转换的小程序项目后不是标准的uni-app项目，但是mac下同样版本hbx转换就没问题。
如图：
![image](https://user-images.githubusercontent.com/7298834/115514862-234e9700-a2b7-11eb-8c2c-c2e5ed1b943e.png)

### 重现步骤
widows下在hbx3.1.9下安装插件，右键小程序项目进行转换

### 期望的结果
生成标准uni-app项目

**Comment by zhangdaren** [comment]
可以说说标准的是哪样嘛？  你这个应该是命令行报错了吧，导致转换失败了，没有完成。

**Comment by lbnt1982** [comment]
项目根目录少了page.json，main.js等文件，运行到微信小程序提示不支持此类应用
只有这个错，其他都转换成功了
[miniprogram to uniapp] 13:32:54.126 [Error] template对应的wxml不存在，无法替换，代码已注释 --> <template is="carousel" :data="imgUrls"></template>   file --> pages/detail/detail

**Comment by zhangdaren** [comment]
看起来是报错了，方便提供一下小程序项目，我这边测试一下不？

**Comment by lbnt1982** [comment]
看来是我自己这个项目的问题，其他的小程序可以正常转换，我先自己排查一下，谢谢你哦

**Comment by lbnt1982** [comment]
排除了那个报错页面，生成日志除了这一条都是成功的，问题还是没解决
[miniprogram to uniapp] 09:06:00.264 Convert components\tips\tips.vue success!
![image](https://user-images.githubusercontent.com/7298834/115804683-13999480-a416-11eb-82ce-c7617a69bc2d.png)

**Comment by lbnt1982** [comment]
[miniprogram to uniapp] 09:06:00.141 Tip: C:\Users\Robbin1982\Desktop\ordmsMiniProgram\ordms\app.wxss包含字体文件，可能需要手工进行修复

**Comment by zhangdaren** [comment]
> [miniprogram to uniapp] 09:06:00.141 Tip: C:\Users\Robbin1982\Desktop\ordmsMiniProgram\ordms\app.wxss包含字体文件，可能需要手工进行修复

这条也不影响哇

**Comment by lbnt1982** [comment]
我把mac生成的文件复制过来，重新识别成了uni-app类型
![image](https://user-images.githubusercontent.com/7298834/116024870-bf92e800-a681-11eb-9d05-dc73a64932d0.png)

**Comment by zhangdaren** [comment]
> 我把mac生成的文件复制过来，重新识别成了uni-app类型
> ![image](https://user-images.githubusercontent.com/7298834/116024870-bf92e800-a681-11eb-9d05-dc73a64932d0.png)

是ok的意思？

**Comment by lbnt1982** [comment]
至少可以编译了，但是一堆需要手工修复的错误

**Comment by zhangdaren** [comment]
正常，，没法100完美转换，根据错误修改吧。。即将发布，将较大副减少要修改的地方。

**Comment by lbnt1982** [comment]
可以关闭问题了，3q
