### ISSUE TITLE
-r参数失效

### ISSUE THREAD

**Issue by yiqianglin** [zhangdaren/miniprogram-to-uniapp#98]
### 问题描述？

参数无效，wtu -i ./src/***** --rename false
发现转化出来的，依旧将wx.转化成uni.了；

### 重现步骤
执行 wtu -i ./src/***** --rename false

### 期望的结果
wx.方法保留

**Comment by yiqianglin** [comment]
而且再问一句，为啥setData不能改成直接赋值？还需要一个setData的mixins呢

**Comment by zhangdaren** [comment]
wx.方法保留

**Comment by yiqianglin** [comment]
> wx.方法保留 这个我记录一下，，理论上应该不影响哇，除了云函数，，，（即将发布的，已区分云函数）

好的，辛苦大佬看看，目前我都是改了之后再替换uni.成wx. ；多人协作比较麻烦

**Comment by zhangdaren** [comment]
> 而且再问一句，为啥setData不能改成直接赋值？还需要一个setData的mixins呢

原因有三：
1.为了尽可能减少代码侵入，基本转换前和转换后代码不会有太大的变化，这样利于二开（强行解释一波了，哈哈）
2. 微信的setData是有回调函数的，有时不太好转换，见下：
3. 复杂度，如下代码：
this.setData({a:1})  看起来轻而易举 --> this.a = 1;

this.setData({a:1}, callback)  有回调函数，也不是不可以  -->  this.a = 1; callback()

"" == 5 ? this.setData({a:1}, callback), this.xx = 2; : this.setData({a:1}, function(){ console.log("")})    混淆过的代码，还掺着匿名回调函数，这。。。不讲武德

综上所述，使用setData，可以更利于从小程序迁入到uniapp，不会改变原有习惯。

当然，万一真需要转换为uniapp的方式，未来也可以考虑做一个可选配置。

**Comment by zhangdaren** [comment]
> > wx.方法保留 这个我记录一下，，理论上应该不影响哇，除了云函数，，，（即将发布的，已区分云函数）
> 
> 好的，辛苦大佬看看，目前我都是改了之后再替换uni.成wx. ；多人协作比较麻烦

为啥要替换？？？？？
uniapp已经是做了兼容处理了哇 ，一样的使用。

**Comment by yiqianglin** [comment]
> > > wx.方法保留 这个我记录一下，，理论上应该不影响哇，除了云函数，，，（即将发布的，已区分云函数）
> > 
> > 
> > 好的，辛苦大佬看看，目前我都是改了之后再替换uni.成wx. ；多人协作比较麻烦
> 
> 为啥要替换？？？？？
> uniapp已经是做了兼容处理了哇 ，一样的使用。

我们是一个子包，也就是说转化成uni-app的组件代码，需要跑在别人的小程序，别人小程序没有uni.xxx，所以会报错；简单来说，我们这边仅仅是用您这个包来转化公共组件；

**Comment by zhangdaren** [comment]
哎哟，居然 是编辑 ，，这个bug下版本修复，找到原因了。

**Comment by yiqianglin** [comment]
> 哎哟，居然 是编辑 ，，这个bug下版本修复，找到原因了。

好的，感谢🙏
