### ISSUE TITLE
转化后依旧出现有this.data.xxx的代码

### ISSUE THREAD

**Issue by yiqianglin** [zhangdaren/miniprogram-to-uniapp#99]
### 问题描述？
在原生组件里面，原本有this.data.xxx的代码
![image](https://user-images.githubusercontent.com/15794229/115831282-f8de1480-a443-11eb-9194-7adc3c5263e1.png)
转化后：
![image](https://user-images.githubusercontent.com/15794229/115831368-14e1b600-a444-11eb-9313-147c5be3a1e9.png)

看起来是triggerEvent里面没有做处理；

### 重现步骤
代码里面triggerEvent只要有this.data.XXX就都不会处理

### 期望的结果
正常处理

**Comment by zhangdaren** [comment]
感谢反馈，，下版针对this.data.xxx的转换已重新优化过，，刚测试已无此问题，，，下版，这几天将发布，敬请期待。

**Comment by yiqianglin** [comment]
> 感谢反馈，，下版针对this.data.xxx的转换已重新优化过，，刚测试已无此问题，，，下版，这几天将发布，敬请期待。

好的，期待大佬新作！还有--rename参数，辛苦大佬一并发布q(๑¯ ε ¯ ๑)p

**Comment by zhangdaren** [comment]
现在发布了v1.1.1可以尝试了一下哈
